/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup apprxtx apprxtx
  @{

    @brief 
      Macro definitions used by the XanBus application
      receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef APPRXTX_H
#define APPRXTX_H

#define XB_mRX_CHECK                        NULL
#define XB_mRX_HANDLER                      NULL

#define XB_mRECV_AC_OUT_STS_RMS             NULL

#define XB_mSEND_ACTIVE_FAULT_STS           NULL

#define XB_mSEND_ACTIVE_WARN_STS            NULL

#define XB_mRECV_AGS_CFG                    NULL
#define XB_mSEND_AGS_CFG                    NULL

#define XB_mRECV_AGS_CFG_AC_I               NULL
#define XB_mSEND_AGS_CFG_AC_I               NULL

#define XB_mRECV_AGS_CFG_BATT_SOC           NULL
#define XB_mSEND_AGS_CFG_BATT_SOC           NULL

#define XB_mRECV_AGS_CFG_CNTCT_CLS          NULL
#define XB_mSEND_AGS_CFG_CNTCT_CLS          NULL

#define XB_mRECV_AGS_CFG_DC_V               NULL
#define XB_mSEND_AGS_CFG_DC_V               NULL

#define XB_mRECV_AGS_CFG_GEN                NULL
#define XB_mSEND_AGS_CFG_GEN                NULL

#define XB_mRECV_AGS_CTRL_CMD               NULL

#define XB_mSEND_AGS_STATS_GEN              NULL

#define XB_mSEND_AGS_STS                    NULL

#define XB_mSEND_AGS_STS_GEN                NULL

#define XB_mRECV_ASSOC_CFG                  NULL
#define XB_mSEND_ASSOC_CFG                  NULL

#define XB_mRECV_ASSOC_STS                  NULL
#define XB_mSEND_ASSOC_STS                  NULL

#define XB_mRECV_CFG                        NULL
#define XB_mSEND_CFG                        NULL

#define XB_mRECV_CHG_STS                    NULL

#define XB_mRECV_CLEAR_CMD                  NULL

#define XB_mRECV_CTRL_CMD                   NULL

#define XB_mRECV_DATE_TIME_STS              NULL

#define XB_mRECV_DC_SRC_STS                 NULL

#define XB_mRECV_DEV_PEEK_ADDR_REQ          NULL

#define XB_mSEND_DEV_PEEK_ADDR_RSP          NULL

#define XB_mRECV_DEV_POKE_ADDR              NULL

#define XB_mRECV_DIAG_CNTCT_CMD             NULL

#define XB_mSEND_DIAG_CNTCT_STS             NULL

#define XB_mRECV_DIAG_INDIC_CMD             NULL

#define XB_mRECV_DIAG_MFG_CFG               NULL
#define XB_mSEND_DIAG_MFG_CFG               NULL

#define XB_mRECV_EN_DIS_CFG                 NULL
#define XB_mSEND_EN_DIS_CFG                 NULL

#define XB_mSEND_FAULT_LOG_STS              NULL

#define XB_mRECV_FEATURE_EN_DIS_CFG         NULL
#define XB_mSEND_FEATURE_EN_DIS_CFG         NULL

#define XB_mSEND_HW_REV_STS                 NULL

#define XB_mSEND_ISO_ACK                    NULL

#define XB_mSEND_PROD_INFO_STS              NULL

#define XB_mRECV_RESET_CMD                  NULL

#define XB_mSEND_STATE_EVT_LOG_STS          NULL

#define XB_mSEND_STS                        NULL

#define XB_mSEND_SW_VER_STS                 NULL

#define XB_mRECV_SYS_ID_CFG                 NULL
#define XB_mSEND_SYS_ID_CFG                 NULL

#define XB_mSEND_SYS_ID_STS                 NULL

#define XB_mSEND_WARN_LOG_STS               NULL


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
