/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup apprxtx apprxtx
  @{

    @brief 
      Macro definitions used by the XanBus application
      receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef APPRXTX_H
#define APPRXTX_H

#define XB_mRX_CHECK                        NULL
#define XB_mRX_HANDLER                      NULL


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
