/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup scrftpgntbl scrftpgntbl
  @{

    @brief 
      Data structures and lookup table used to convert CAN message buffers
      to and from the structures used by the application level code.


  @note
    - Autogenerated.

*******************************************************************************/

#include "config.h"

#include "scrftudefs.h"
#include "scrftrxtx.h"
#include "scrftapprxtx.h"


#ifndef WIN32
#pragma CONST_SEG PGN_DESC
#endif

// Describe the fields of each PGN

// AC Input Status 1
static const PGN_tzFIELD_DESC XT_FAR azAcInSts1Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->ucAcSrcNum ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->ucNumLines ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->ucNumLines ) },
    { PGN_eTYPE_BIT,  16,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->teLine ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->teLine ) },
    { PGN_eTYPE_BIT,  18,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->teAcceptability ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->teAcceptability ) },
    { PGN_eTYPE_SCHAR,  24,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->scPwrFac ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS1 *)NULL )->scPwrFac ) }
};

// AC Input Status 2
static const PGN_tzFIELD_DESC XT_FAR azAcInSts2Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->ucAcSrcNum ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_BIT,   8,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->teLine ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->teLine ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->uiVoltage ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->uiVoltage ) },
    { PGN_eTYPE_UINT,  32,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->uiCurrent ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->uiCurrent ) },
    { PGN_eTYPE_UINT,  48,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->uiFreq ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS2 *)NULL )->uiFreq ) }
};

// AC Input Status 3
static const PGN_tzFIELD_DESC XT_FAR azAcInSts3Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->ucAcSrcNum ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_BIT,   8,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->teLine ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->teLine ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->uiRealPwr ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->uiRealPwr ) },
    { PGN_eTYPE_UINT,  32,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->uiReactivePwr ) ), sizeof( ((SCRFT_tzPGN_AC_IN_STS3 *)NULL )->uiReactivePwr ) }
};

// AC Output Status 1
static const PGN_tzFIELD_DESC XT_FAR azAcOutSts1Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->ucAcSrcNum ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->ucNumLines ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->ucNumLines ) },
    { PGN_eTYPE_BIT,  16,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->teLine ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->teLine ) },
    { PGN_eTYPE_BIT,  18,   3, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->teWaveform ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->teWaveform ) },
    { PGN_eTYPE_SCHAR,  24,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->scPwrFac ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS1 *)NULL )->scPwrFac ) }
};

// AC Output Status 2
static const PGN_tzFIELD_DESC XT_FAR azAcOutSts2Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->ucAcSrcNum ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_BIT,   8,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->teLine ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->teLine ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->uiVoltage ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->uiVoltage ) },
    { PGN_eTYPE_UINT,  32,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->uiCurrent ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->uiCurrent ) },
    { PGN_eTYPE_UINT,  48,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->uiFreq ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS2 *)NULL )->uiFreq ) }
};

// AC Output Status 3
static const PGN_tzFIELD_DESC XT_FAR azAcOutSts3Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->ucAcSrcNum ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_BIT,   8,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->teLine ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->teLine ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->uiRealPwr ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->uiRealPwr ) },
    { PGN_eTYPE_UINT,  32,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->uiReactivePwr ) ), sizeof( ((SCRFT_tzPGN_AC_OUT_STS3 *)NULL )->uiReactivePwr ) }
};

// AGS Status
static const PGN_tzFIELD_DESC XT_FAR azAgsStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   4, (uint16)( (uint32)&( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucAgsOpState ) ), sizeof( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucAgsOpState ) },
    { PGN_eTYPE_BIT,   4,   4, (uint16)( (uint32)&( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucGenState ) ), sizeof( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucGenState ) },
    { PGN_eTYPE_BIT,   8,   4, (uint16)( (uint32)&( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucGenOnReason ) ), sizeof( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucGenOnReason ) },
    { PGN_eTYPE_BIT,  12,   5, (uint16)( (uint32)&( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucGenOffReason ) ), sizeof( ((SCRFT_tzPGN_AGS_STS *)NULL )->ucGenOffReason ) },
    { PGN_eTYPE_BIT,  17,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_AGS_STS *)NULL )->teAgsToGenSig ) ), sizeof( ((SCRFT_tzPGN_AGS_STS *)NULL )->teAgsToGenSig ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_AGS_STS *)NULL )->uiTimeIntvl ) ), sizeof( ((SCRFT_tzPGN_AGS_STS *)NULL )->uiTimeIntvl ) },
};

// Battery Detailed Status
static const PGN_tzFIELD_DESC XT_FAR azBattDetailStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->ucBattInst ) ), sizeof( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->ucBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoc ) ), sizeof( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoc ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoh ) ), sizeof( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoh ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->uiTimeRemain ) ), sizeof( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->uiTimeRemain ) },
    { PGN_eTYPE_UINT,  48,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->uiRippleVoltage ) ), sizeof( ((SCRFT_tzPGN_BATT_DETAIL_STS *)NULL )->uiRippleVoltage ) }
};

// Battery Status
static const PGN_tzFIELD_DESC XT_FAR azBattStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_STS *)NULL )->ucBattInst ) ), sizeof( ((SCRFT_tzPGN_BATT_STS *)NULL )->ucBattInst ) },
    { PGN_eTYPE_SINT,   8,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_STS *)NULL )->siBattPot ) ), sizeof( ((SCRFT_tzPGN_BATT_STS *)NULL )->siBattPot ) },
    { PGN_eTYPE_SINT,  24,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_STS *)NULL )->siBattCurr ) ), sizeof( ((SCRFT_tzPGN_BATT_STS *)NULL )->siBattCurr ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_STS *)NULL )->uiBattCaseTemp ) ), sizeof( ((SCRFT_tzPGN_BATT_STS *)NULL )->uiBattCaseTemp ) },
    { PGN_eTYPE_UCHAR,  56,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_BATT_STS *)NULL )->ucSid ) ), sizeof( ((SCRFT_tzPGN_BATT_STS *)NULL )->ucSid ) }
};

// Charger Status
static const PGN_tzFIELD_DESC XT_FAR azChgStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_CHG_STS *)NULL )->ucDCSrcNum ) ), sizeof( ((SCRFT_tzPGN_CHG_STS *)NULL )->ucDCSrcNum ) },
    { PGN_eTYPE_BIT,   8,   5, (uint16)( (uint32)&( ((SCRFT_tzPGN_CHG_STS *)NULL )->teOpState ) ), sizeof( ((SCRFT_tzPGN_CHG_STS *)NULL )->teOpState ) },
    { PGN_eTYPE_BIT,  13,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_CHG_STS *)NULL )->teChgMode ) ), sizeof( ((SCRFT_tzPGN_CHG_STS *)NULL )->teChgMode ) },
    { PGN_eTYPE_BIT,  15,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_CHG_STS *)NULL )->teChgEnDis ) ), sizeof( ((SCRFT_tzPGN_CHG_STS *)NULL )->teChgEnDis ) },
    { PGN_eTYPE_BIT,  17,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_CHG_STS *)NULL )->teBattTempSensPres ) ), sizeof( ((SCRFT_tzPGN_CHG_STS *)NULL )->teBattTempSensPres ) },
    { PGN_eTYPE_BIT,  19,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_CHG_STS *)NULL )->teEqlzPending ) ), sizeof( ((SCRFT_tzPGN_CHG_STS *)NULL )->teEqlzPending ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_CHG_STS *)NULL )->uiEqlzTimeRemain ) ), sizeof( ((SCRFT_tzPGN_CHG_STS *)NULL )->uiEqlzTimeRemain ) },
};

// Inverter Status
static const PGN_tzFIELD_DESC XT_FAR azInvStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((SCRFT_tzPGN_INV_STS *)NULL )->ucACSrcNum ) ), sizeof( ((SCRFT_tzPGN_INV_STS *)NULL )->ucACSrcNum ) },
    { PGN_eTYPE_BIT,   8,   4, (uint16)( (uint32)&( ((SCRFT_tzPGN_INV_STS *)NULL )->teOpState ) ), sizeof( ((SCRFT_tzPGN_INV_STS *)NULL )->teOpState ) },
    { PGN_eTYPE_BIT,  12,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_INV_STS *)NULL )->teInvEnDis ) ), sizeof( ((SCRFT_tzPGN_INV_STS *)NULL )->teInvEnDis ) },
    { PGN_eTYPE_BIT,  14,   2, (uint16)( (uint32)&( ((SCRFT_tzPGN_INV_STS *)NULL )->teBattTempSensPres ) ), sizeof( ((SCRFT_tzPGN_INV_STS *)NULL )->teBattTempSensPres ) },
};

// Describe the descriptor of each PGN

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescAcInSts1 =
{
        -1,
        6,
        SCRFT_mRECV_AC_IN_STS1,
        SCRFT_mSEND_AC_IN_STS1,
        SCRFT_DLC_AC_IN_STS1,
        sizeof( SCRFT_tzPGN_AC_IN_STS1 ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcInSts1Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescAcInSts2 =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_AC_IN_STS2,
        SCRFT_DLC_AC_IN_STS2,
        sizeof( SCRFT_tzPGN_AC_IN_STS2 ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcInSts2Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescAcInSts3 =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_AC_IN_STS3,
        SCRFT_DLC_AC_IN_STS3,
        sizeof( SCRFT_tzPGN_AC_IN_STS3 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcInSts3Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescAcOutSts1 =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_AC_OUT_STS1,
        SCRFT_DLC_AC_OUT_STS1,
        sizeof( SCRFT_tzPGN_AC_OUT_STS1 ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcOutSts1Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescAcOutSts2 =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_AC_OUT_STS2,
        SCRFT_DLC_AC_OUT_STS2,
        sizeof( SCRFT_tzPGN_AC_OUT_STS2 ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcOutSts2Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescAcOutSts3 =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_AC_OUT_STS3,
        SCRFT_DLC_AC_OUT_STS3,
        sizeof( SCRFT_tzPGN_AC_OUT_STS3 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcOutSts3Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescAgsSts =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_AGS_STS,
        SCRFT_DLC_AGS_STS,
        sizeof( SCRFT_tzPGN_AGS_STS ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azAgsStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescBattDetailSts =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_BATT_DETAIL_STS,
        SCRFT_DLC_BATT_DETAIL_STS,
        sizeof( SCRFT_tzPGN_BATT_DETAIL_STS ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattDetailStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescBattSts =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_BATT_STS,
        SCRFT_DLC_BATT_STS,
        sizeof( SCRFT_tzPGN_BATT_STS ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescChgSts =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_CHG_STS,
        SCRFT_DLC_CHG_STS,
        sizeof( SCRFT_tzPGN_CHG_STS ),
        7,
        (const PGN_tzFIELD_DESC * XT_FAR) azChgStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR SCRFT_tzDescInvSts =
{
        -1,
        6,
        NULL,
        SCRFT_mSEND_INV_STS,
        SCRFT_DLC_INV_STS,
        sizeof( SCRFT_tzPGN_INV_STS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azInvStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

#ifndef WIN32
#pragma CONST_SEG DEFAULT
#endif

// List of receivable PGNs
const uint32 SCRFT_kaulRX_PGN_LIST[] = 
{
	SCRFT_PGN_AC_IN_STS1,
};

uint16 SCRFTPGNTBL_fnSizeOfRxPgnList( void )
{
    return ( XT_mDIM( SCRFT_kaulRX_PGN_LIST ) );
}

// List of Transmittable PGNs
const uint32 SCRFT_kaulTX_PGN_LIST[] = 
{
	SCRFT_PGN_BATT_STS,
	SCRFT_PGN_AC_OUT_STS3,
	SCRFT_PGN_AC_OUT_STS2,
	SCRFT_PGN_AC_IN_STS3,
	SCRFT_PGN_AC_IN_STS2,
	SCRFT_PGN_BATT_DETAIL_STS,
	SCRFT_PGN_INV_STS,
	SCRFT_PGN_AGS_STS,
	SCRFT_PGN_CHG_STS,
	SCRFT_PGN_AC_OUT_STS1,
	SCRFT_PGN_AC_IN_STS1,
};

uint16 SCRFTPGNTBL_fnSizeOfTxPgnList( void )
{
    return ( XT_mDIM( SCRFT_kaulTX_PGN_LIST ) );
}

// List of all PGNS with descriptors for those used by PROTOCOL_SmartCraft
const PGN_tzPGN_INFO SCRFT_katzALL_PGN_LIST[] =
{
    { SCRFT_PGN_BATT_STS,               -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescBattSts },

    { SCRFT_PGN_AC_OUT_STS3,            -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescAcOutSts3 },

    { SCRFT_PGN_AC_OUT_STS2,            -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescAcOutSts2 },

    { SCRFT_PGN_AC_IN_STS3,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescAcInSts3 },

    { SCRFT_PGN_AC_IN_STS2,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescAcInSts2 },

    { SCRFT_PGN_BATT_DETAIL_STS,        -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescBattDetailSts },

    { SCRFT_PGN_INV_STS,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescInvSts },

    { SCRFT_PGN_AGS_STS,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescAgsSts },

    { SCRFT_PGN_CHG_STS,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescChgSts },

    { SCRFT_PGN_AC_OUT_STS1,            -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescAcOutSts1 },

    { SCRFT_PGN_AC_IN_STS1,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &SCRFT_tzDescAcInSts1 },

};

uint16 SCRFTPGNTBL_fnSizeOfAllPgnList( void )
{
    return ( XT_mDIM( SCRFT_katzALL_PGN_LIST ) );
}

// Number of entries in dynamic support arrays rounded up to byte boundary
#define   SCRFT_DYNAMIC_COUNT    ( ( XT_mDIM( SCRFT_katzALL_PGN_LIST ) + XT_BITS_PER_BYTE - 1 ) / XT_BITS_PER_BYTE )

uchar8 SCRFT_aucDynamicRx[ SCRFT_DYNAMIC_COUNT ];

uint16 SCRFTPGNTBL_fnSizeOfDynRxLists( void )
{
    return ( XT_mDIM( SCRFT_aucDynamicRx ) );
}

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
