/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup apprxtx apprxtx
  @{

    @brief 
      Macro definitions used by the XanBus application
      receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef APPRXTX_H
#define APPRXTX_H

#define XB_mRX_CHECK                        NULL
#define XB_mRX_HANDLER                      NULL

#define XB_mRECV_AC_IN_STS_RMS              NULL

#define XB_mRECV_AC_OUT_STS_RMS             NULL

#define XB_mRECV_AC_STS_RMS                 NULL

#define XB_mRECV_ACTIVE_FAULT_STS           NULL
#define XB_mSEND_ACTIVE_FAULT_STS           NULL

#define XB_mRECV_ACTIVE_FAULT_STS2          NULL
#define XB_mSEND_ACTIVE_FAULT_STS2          NULL

#define XB_mRECV_ACTIVE_WARN_STS            NULL
#define XB_mSEND_ACTIVE_WARN_STS            NULL

#define XB_mRECV_ACTIVE_WARN_STS2           NULL
#define XB_mSEND_ACTIVE_WARN_STS2           NULL

#define XB_mSEND_AGS_CTRL_CMD               NULL

#define XB_mRECV_AGS_STS                    NULL

#define XB_mRECV_ASSOC_STS                  NULL

#define XB_mSEND_BATT_MON_CTRL_CMD          NULL

#define XB_mRECV_BATT_STS2                  NULL

#define XB_mRECV_CFG                        NULL
#define XB_mSEND_CFG                        NULL

#define XB_mSEND_CHG_CTRL_CMD               NULL

#define XB_mSEND_CHG_CTRL_CMD2              NULL

#define XB_mRECV_CHG_STS                    NULL

#define XB_mRECV_CLEAR_CMD                  NULL

#define XB_mRECV_COMPLEX_REQ                NULL

#define XB_mRECV_CTRL_CMD                   NULL

#define XB_mSEND_CV_CI_CTRL_CMD             NULL

#define XB_mRECV_DATE_TIME_STS              NULL
#define XB_mSEND_DATE_TIME_STS              NULL

#define XB_mRECV_DC_SRC_STS                 NULL

#define XB_mRECV_DC_SRC_STS2                NULL

#define XB_mRECV_DEBUG_FP                   NULL
#define XB_mSEND_DEBUG_FP                   NULL

#define XB_mRECV_DEV_PEEK_ADDR_REQ          NULL

#define XB_mSEND_DEV_PEEK_ADDR_RSP          NULL

#define XB_mRECV_DEV_POKE_ADDR              NULL

#define XB_mRECV_DIAG_CNTCT_CMD             NULL

#define XB_mSEND_DIAG_CNTCT_STS             NULL

#define XB_mRECV_DIAG_FAN_CMD               NULL

#define XB_mRECV_DIAG_INDIC_CMD             NULL

#define XB_mRECV_DIAG_MFG_CFG               NULL
#define XB_mSEND_DIAG_MFG_CFG               NULL

#define XB_mRECV_EN_DIS_CFG                 NULL
#define XB_mSEND_EN_DIS_CFG                 NULL

#define XB_mRECV_FAN_STATS                  NULL

#define XB_mRECV_FAN_STS                    NULL

#define XB_mSEND_FAULT_LOG_STS              NULL

#define XB_mSEND_FAULT_LOG_STS2             NULL

#define XB_mRECV_FEATURE_EN_DIS_CFG         NULL
#define XB_mSEND_FEATURE_EN_DIS_CFG         NULL

#define XB_mSEND_GRID_TIE_CTRL_CMD          NULL

#define XB_mRECV_GW_CFG                     NULL
#define XB_mSEND_GW_CFG                     NULL

#define XB_mRECV_GW_CFG_ADDR_TRANS_OTH_INTF    NULL
#define XB_mSEND_GW_CFG_ADDR_TRANS_OTH_INTF    NULL

#define XB_mRECV_GW_CFG_ADDR_TRANS_XB_INTF    NULL
#define XB_mSEND_GW_CFG_ADDR_TRANS_XB_INTF    NULL

#define XB_mRECV_GW_CFG_ID_TRANS            NULL
#define XB_mSEND_GW_CFG_ID_TRANS            NULL

#define XB_mRECV_GW_CFG_MSG_FILTERS_OTH_INTF    NULL
#define XB_mSEND_GW_CFG_MSG_FILTERS_OTH_INTF    NULL

#define XB_mRECV_GW_CFG_MSG_FILTERS_XB_INTF    NULL
#define XB_mSEND_GW_CFG_MSG_FILTERS_XB_INTF    NULL

#define XB_mSEND_GW_STATS                   NULL

#define XB_mSEND_GW_STS                     NULL

#define XB_mSEND_HW_REV_STS                 NULL

#define XB_mRECV_INT_TEMP_CFG_OT            NULL
#define XB_mSEND_INT_TEMP_CFG_OT            NULL

#define XB_mRECV_INT_TEMP_CFG_UT            NULL
#define XB_mSEND_INT_TEMP_CFG_UT            NULL

#define XB_mSEND_INT_TEMP_STATS2            NULL

#define XB_mSEND_INV_CTRL_CMD               NULL

#define XB_mRECV_INV_STS                    NULL

#define XB_mRECV_INV_STS2                   NULL

#define XB_mRECV_ISO_ACK                    NULL
#define XB_mSEND_ISO_ACK                    NULL

#define XB_mRECV_PROD_INFO_STS              NULL
#define XB_mSEND_PROD_INFO_STS              NULL

#define XB_mRECV_RESET_CMD                  NULL

#define XB_mSEND_STATE_EVT_LOG_STS          NULL

#define XB_mSEND_STATE_EVT_LOG_STS2         NULL

#define XB_mRECV_STRING_CFG                 NULL
#define XB_mSEND_STRING_CFG                 NULL

#define XB_mRECV_STS                        NULL
#define XB_mSEND_STS                        NULL

#define XB_mSEND_SW_VER_STS                 NULL

#define XB_mRECV_SYS_ID_CFG                 NULL
#define XB_mSEND_SYS_ID_CFG                 NULL

#define XB_mSEND_SYS_ID_STS                 NULL

#define XB_mSEND_WARN_LOG_STS               NULL

#define XB_mSEND_WARN_LOG_STS2              NULL


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
