/******************************************************************************

  (c) 2003 - 2020 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup rvcrxtx rvcrxtx
  @{

    @brief 
      Macro definitions used by the RV-C library receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef RVCRXTX_H
#define RVCRXTX_H

// PG Functions include file
#include "xbpgfns.h"

#define RVC_mRECV_ISO_ADDR_CLAIM            XBADDR_fnRecvClaim
#define RVC_mSEND_ISO_ADDR_CLAIM            XBADDR_fnWantClaim

#define RVC_mRECV_ISO_CMD_ADDR              XBADDR_fnRecvCmdAddr

#define RVC_mRECV_ISO_REQ                   XBMSG_fnRecvISOReq  // Handled by XB library
#define RVC_mSEND_ISO_REQ                   NULL    // Handled by lower layer

#define RVC_mRECV_ISO_TP_CONN_MAN_ABORT     XBMSG_fnRecvConnMgmt  // Handled by XB library
#define RVC_mSEND_ISO_TP_CONN_MAN_ABORT     NULL    // Handled by lower layer

#define RVC_mRECV_ISO_TP_CONN_MAN_BAM       XBMSG_fnRecvConnMgmt  // Handled by XB library
#define RVC_mSEND_ISO_TP_CONN_MAN_BAM       NULL    // Handled by lower layer

#define RVC_mRECV_ISO_TP_CONN_MAN_CTS       XBMSG_fnRecvConnMgmt  // Handled by XB library
#define RVC_mSEND_ISO_TP_CONN_MAN_CTS       NULL    // Handled by lower layer

#define RVC_mRECV_ISO_TP_CONN_MAN_EOM       XBMSG_fnRecvConnMgmt  // Handled by XB library
#define RVC_mSEND_ISO_TP_CONN_MAN_EOM       NULL    // Handled by lower layer

#define RVC_mRECV_ISO_TP_CONN_MAN_RTS       XBMSG_fnRecvConnMgmt  // Handled by XB library
#define RVC_mSEND_ISO_TP_CONN_MAN_RTS       NULL    // Handled by lower layer

#define RVC_mRECV_ISO_TP_XFER               NULL    // Handled by lower layer
#define RVC_mSEND_ISO_TP_XFER               NULL    // Handled by lower layer

#define RVC_mRECV_DIAG_MSG1                 XBADDR_fnRecvDiagMsg1

#endif // RVCRXTX_H


//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
