/*=============================================================================
Copyright 2003 Xantrex International.  All rights reserved.

This source file is proprietary to Xantrex International. and protected by 
copyright. The reproduction, in whole or in part, by anyone without the written 
approval of Xantrex is prohibited.

FILE NAME:  xbrxtx.h

PURPOSE:
   
   This file contains the macros for the receive and send
   handlers for the PGNs used by XanBus.
   
FUNCTION(S):
   None
   
NOTES:
   This file is no longer auto-generated.  Rather the output of the 
   autogenerated file 
   G:\.accurev\XanBus\Software\Utilities\DB2CCodeGen\bin\xbrxtx.h must be 
   merged into this one.

CHANGE HISTORY:
$Log: xbrxtx.h $

    ***********************************************
    Revision: XanBus_HollyZ/1
    User: HollyZ     Date: 05/25/06  Time: 07:12PM
    Revert Xb stack to V1.2.7

    ***********************************************
    Revision: XanBus_HenryW/9
    User: HenryW     Date: 01/11/06  Time: 12:05AM
    - saving

    ***********************************************
    Revision: XanBus_HenryW/8
    User: HenryW     Date: 01/09/06  Time: 08:04PM
    - saving 

    ***********************************************
    Revision: XanBus_HenryW/6
    User: HenryW     Date: 09/16/05  Time: 10:48PM
    - improved message support
    - added support for TI281x

    ***********************************************
    Revision: XanBus_HenryW/5
    User: HenryW     Date: 08/19/05  Time: 08:07PM
    - cleaned up history list.

    ***********************************************
    Revision: GateWayPfrmANMEA_DaleM/1
    User: DaleM     Date: 02/10/05  Time: 07:19PM
    Cleaned up old history list
    

=============================================================================*/

#ifndef XBRXTX_H
#define XBRXTX_H

// PG Functions include file
#include "xbpgfns.h"

#define XB_mRECV_COMM_STATS                 NULL    // Only receivable by a UI or DIAG
#define XB_mSEND_COMM_STATS                 XBMSG_fnWantCommStats

#define XB_mRECV_ISO_ADDR_CLAIM             XBADDR_fnRecvClaim
#define XB_mSEND_ISO_ADDR_CLAIM             XBADDR_fnWantClaim

#define XB_mRECV_ISO_CMD_ADDR               XBADDR_fnRecvCmdAddr
#define XB_mSEND_ISO_CMD_ADDR               NULL    // Not requestable

#define XB_mRECV_ISO_REQ                    XBMSG_fnRecvISOReq
#define XB_mSEND_ISO_REQ                    NULL

#define XB_mRECV_ISO_TP_CONN_MAN_ABORT      XBMSG_fnRecvConnMgmt  // Handled by XB library
#define XB_mSEND_ISO_TP_CONN_MAN_ABORT      NULL    // Handled by lower layer

#define XB_mRECV_ISO_TP_CONN_MAN_BAM        XBMSG_fnRecvConnMgmt  // Handled by XB library
#define XB_mSEND_ISO_TP_CONN_MAN_BAM        NULL    // Handled by lower layer

#define XB_mRECV_ISO_TP_CONN_MAN_CTS        XBMSG_fnRecvConnMgmt  // Handled by XB library
#define XB_mSEND_ISO_TP_CONN_MAN_CTS        NULL    // Handled by lower layer

#define XB_mRECV_ISO_TP_CONN_MAN_EOM        XBMSG_fnRecvConnMgmt  // Handled by XB library
#define XB_mSEND_ISO_TP_CONN_MAN_EOM        NULL    // Handled by lower layer

#define XB_mRECV_ISO_TP_CONN_MAN_RTS        XBMSG_fnRecvConnMgmt  // Handled by XB library
#define XB_mSEND_ISO_TP_CONN_MAN_RTS        NULL    // Handled by lower layer

#define XB_mRECV_ISO_TP_XFER                NULL    // Handled by lower layer
#define XB_mSEND_ISO_TP_XFER                NULL    // Handled by lower layer

#define XB_mRECV_NAME_CFG                   XBADDR_fnRecvNAMECfg
#define XB_mSEND_NAME_CFG                   XBADDR_fnWantNAMECfg

#define XB_mRECV_PER_XMIT_CFG               XBTIMERS_fnRecvPerXmitCfg
#define XB_mSEND_PER_XMIT_CFG               XBTIMERS_fnWantPerXmitCfg

#define XB_mRECV_PGN_LIST_RX                NULL    // Only receivable by a UI or DIAG
#define XB_mSEND_PGN_LIST_RX                XBMSG_fnWantPgnList

#define XB_mRECV_PGN_LIST_TX                NULL    // Only receivable by a UI or DIAG
#define XB_mSEND_PGN_LIST_TX                XBMSG_fnWantPgnList

#define XB_mRECV_RX_TO_CFG                  XBTIMERS_fnRecvRxToCfg
#define XB_mSEND_RX_TO_CFG                  XBTIMERS_fnWantRxToCfg


#endif
