/******************************************************************************

  (c) 2003 - 2024 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup rvcpgntbl rvcpgntbl
  @{

    @brief 
      Data structures and lookup table used to convert CAN message buffers
      to and from the structures used by the application level code.


  @note
    - Autogenerated.

*******************************************************************************/

#include "config.h"

#include "rvcudefs.h"
#include "rvcrxtx.h"
#include "rvcapprxtx.h"


#if !defined( WIN32 ) && !defined(__TMS320C2000__)
#pragma CONST_SEG PGN_DESC
#endif

// Describe the fields of each PGN

// Alarm Command
static const PGN_tzFIELD_DESC XT_FAR azAlarmCmdFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_CMD *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_ALARM_CMD *)NULL )->ucInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_CMD *)NULL )->teDevType ) ), sizeof( ((RVC_tzPGN_ALARM_CMD *)NULL )->teDevType ) },
    { PGN_eTYPE_BIT,  18,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_CMD *)NULL )->teReadyAlarm ) ), sizeof( ((RVC_tzPGN_ALARM_CMD *)NULL )->teReadyAlarm ) },
    { PGN_eTYPE_BIT,  20,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_CMD *)NULL )->teAckAlarm ) ), sizeof( ((RVC_tzPGN_ALARM_CMD *)NULL )->teAckAlarm ) },
    { PGN_eTYPE_BIT,  22,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_CMD *)NULL )->teAutoRstEn ) ), sizeof( ((RVC_tzPGN_ALARM_CMD *)NULL )->teAutoRstEn ) },
    { PGN_eTYPE_BIT,  24,   8, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_CMD *)NULL )->ucDevInst ) ), sizeof( ((RVC_tzPGN_ALARM_CMD *)NULL )->ucDevInst ) }
};

// Alarm Status
static const PGN_tzFIELD_DESC XT_FAR azAlarmStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->ucInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teDevType ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teDevType ) },
    { PGN_eTYPE_BIT,  16,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmTrig ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmTrig ) },
    { PGN_eTYPE_BIT,  18,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmRdy ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmRdy ) },
    { PGN_eTYPE_BIT,  20,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmAckd ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmAckd ) },
    { PGN_eTYPE_BIT,  22,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmRstEn ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmRstEn ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->uiElapsedTime ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->uiElapsedTime ) },
    { PGN_eTYPE_BIT,  40,   8, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->ucDevInst ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->ucDevInst ) },
    { PGN_eTYPE_BIT,  48,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teFtMonReq ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teFtMonReq ) },
    { PGN_eTYPE_BIT,  50,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmForLog ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmForLog ) },
    { PGN_eTYPE_BIT,  52,   2, (uint16)( (uint32)&( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmForUser ) ), sizeof( ((RVC_tzPGN_ALARM_STS *)NULL )->teAlarmForUser ) },
};

// Battery Command
static const PGN_tzFIELD_DESC XT_FAR azBattCmdFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_CMD *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_CMD *)NULL )->teBattInst ) },
    { PGN_eTYPE_BIT,   8,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_CMD *)NULL )->teDesiredLoadOnOffSts ) ), sizeof( ((RVC_tzPGN_BATT_CMD *)NULL )->teDesiredLoadOnOffSts ) },
    { PGN_eTYPE_BIT,  10,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_CMD *)NULL )->teDesiredChgOnOffSts ) ), sizeof( ((RVC_tzPGN_BATT_CMD *)NULL )->teDesiredChgOnOffSts ) },
    { PGN_eTYPE_BIT,  12,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_CMD *)NULL )->teClrHistory ) ), sizeof( ((RVC_tzPGN_BATT_CMD *)NULL )->teClrHistory ) },
    { PGN_eTYPE_BIT,  14,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_CMD *)NULL )->teReserved ) ), sizeof( ((RVC_tzPGN_BATT_CMD *)NULL )->teReserved ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_CMD *)NULL )->ucRtnModuleCellDetail ) ), sizeof( ((RVC_tzPGN_BATT_CMD *)NULL )->ucRtnModuleCellDetail ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_CMD *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_CMD *)NULL )->teDcInst ) }
};

// Battery Status 1
static const PGN_tzFIELD_DESC XT_FAR azBattSts1Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS1 *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_STS1 *)NULL )->teBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS1 *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_STS1 *)NULL )->teDcInst ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS1 *)NULL )->uiDcV ) ), sizeof( ((RVC_tzPGN_BATT_STS1 *)NULL )->uiDcV ) },
    { PGN_eTYPE_ULONG,  32,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS1 *)NULL )->ulDcI ) ), sizeof( ((RVC_tzPGN_BATT_STS1 *)NULL )->ulDcI ) }
};

// Battery Status 11
static const PGN_tzFIELD_DESC XT_FAR azBattSts11Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->teBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->teDcInst ) },
    { PGN_eTYPE_BIT,  16,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->teDischgOnOffSts ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->teDischgOnOffSts ) },
    { PGN_eTYPE_BIT,  18,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->teChgOnOffSts ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->teChgOnOffSts ) },
    { PGN_eTYPE_BIT,  20,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->teChgDetect ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->teChgDetect ) },
    { PGN_eTYPE_BIT,  22,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->teReservSts ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->teReservSts ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->uiNomFullCap ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->uiNomFullCap ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS11 *)NULL )->uiDcPwr ) ), sizeof( ((RVC_tzPGN_BATT_STS11 *)NULL )->uiDcPwr ) }
};

// Battery Status 2
static const PGN_tzFIELD_DESC XT_FAR azBattSts2Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS2 *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_STS2 *)NULL )->teBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS2 *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_STS2 *)NULL )->teDcInst ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS2 *)NULL )->uiSrcTemp ) ), sizeof( ((RVC_tzPGN_BATT_STS2 *)NULL )->uiSrcTemp ) },
    { PGN_eTYPE_UCHAR,  32,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS2 *)NULL )->ucSoc ) ), sizeof( ((RVC_tzPGN_BATT_STS2 *)NULL )->ucSoc ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS2 *)NULL )->uiTimeRemain ) ), sizeof( ((RVC_tzPGN_BATT_STS2 *)NULL )->uiTimeRemain ) },
    { PGN_eTYPE_BIT,  56,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS2 *)NULL )->teTimeRemainInterp ) ), sizeof( ((RVC_tzPGN_BATT_STS2 *)NULL )->teTimeRemainInterp ) }
};

// Battery Status 3
static const PGN_tzFIELD_DESC XT_FAR azBattSts3Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS3 *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_STS3 *)NULL )->teBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS3 *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_STS3 *)NULL )->teDcInst ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS3 *)NULL )->ucSoh ) ), sizeof( ((RVC_tzPGN_BATT_STS3 *)NULL )->ucSoh ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS3 *)NULL )->uiCapRemain ) ), sizeof( ((RVC_tzPGN_BATT_STS3 *)NULL )->uiCapRemain ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS3 *)NULL )->ucRelCap ) ), sizeof( ((RVC_tzPGN_BATT_STS3 *)NULL )->ucRelCap ) },
    { PGN_eTYPE_UINT,  48,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS3 *)NULL )->uiAcRmsRipple ) ), sizeof( ((RVC_tzPGN_BATT_STS3 *)NULL )->uiAcRmsRipple ) }
};

// Battery Status 4
static const PGN_tzFIELD_DESC XT_FAR azBattSts4Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS4 *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_STS4 *)NULL )->teBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS4 *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_STS4 *)NULL )->teDcInst ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS4 *)NULL )->teDesChgState ) ), sizeof( ((RVC_tzPGN_BATT_STS4 *)NULL )->teDesChgState ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS4 *)NULL )->uiDesDcV ) ), sizeof( ((RVC_tzPGN_BATT_STS4 *)NULL )->uiDesDcV ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS4 *)NULL )->uiDesDcI ) ), sizeof( ((RVC_tzPGN_BATT_STS4 *)NULL )->uiDesDcI ) },
    { PGN_eTYPE_BIT,  56,   4, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS4 *)NULL )->teBattType ) ), sizeof( ((RVC_tzPGN_BATT_STS4 *)NULL )->teBattType ) }
};

// Battery Status 6
static const PGN_tzFIELD_DESC XT_FAR azBattSts6Fields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teDcInst ) },
    { PGN_eTYPE_BIT,  16,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiVoltLimitSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiVoltLimitSts ) },
    { PGN_eTYPE_BIT,  18,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiVoltDisconSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiVoltDisconSts ) },
    { PGN_eTYPE_BIT,  20,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowVoltLimitSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowVoltLimitSts ) },
    { PGN_eTYPE_BIT,  22,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowVoltDisconSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowVoltDisconSts ) },
    { PGN_eTYPE_BIT,  24,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowSocLimitSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowSocLimitSts ) },
    { PGN_eTYPE_BIT,  26,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowSocDisconSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowSocDisconSts ) },
    { PGN_eTYPE_BIT,  28,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowDcSrcTempLimitSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowDcSrcTempLimitSts ) },
    { PGN_eTYPE_BIT,  30,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowDcSrcTempDisconSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teLowDcSrcTempDisconSts ) },
    { PGN_eTYPE_BIT,  32,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiDcSrcTempLimitSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiDcSrcTempLimitSts ) },
    { PGN_eTYPE_BIT,  34,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiDcSrcTempDisconSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiDcSrcTempDisconSts ) },
    { PGN_eTYPE_BIT,  36,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiAmpDcSrcLimitSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiAmpDcSrcLimitSts ) },
    { PGN_eTYPE_BIT,  38,   2, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiAmpDcSrcDisconSts ) ), sizeof( ((RVC_tzPGN_BATT_STS6 *)NULL )->teHiAmpDcSrcDisconSts ) }
};

// Battery Summary
static const PGN_tzFIELD_DESC XT_FAR azBattSummFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_SUMM *)NULL )->teBattInst ) ), sizeof( ((RVC_tzPGN_BATT_SUMM *)NULL )->teBattInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_SUMM *)NULL )->teDcInst ) ), sizeof( ((RVC_tzPGN_BATT_SUMM *)NULL )->teDcInst ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_SUMM *)NULL )->ucSeriesString ) ), sizeof( ((RVC_tzPGN_BATT_SUMM *)NULL )->ucSeriesString ) },
    { PGN_eTYPE_BIT,  24,   8, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_SUMM *)NULL )->teModuleCnt ) ), sizeof( ((RVC_tzPGN_BATT_SUMM *)NULL )->teModuleCnt ) },
    { PGN_eTYPE_UCHAR,  32,   1, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_SUMM *)NULL )->ucCellsPerModule ) ), sizeof( ((RVC_tzPGN_BATT_SUMM *)NULL )->ucCellsPerModule ) },
    { PGN_eTYPE_BIT,  56,   3, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_SUMM *)NULL )->teVoltSts ) ), sizeof( ((RVC_tzPGN_BATT_SUMM *)NULL )->teVoltSts ) },
    { PGN_eTYPE_BIT,  59,   3, (uint16)( (uint32)&( ((RVC_tzPGN_BATT_SUMM *)NULL )->teTempSts ) ), sizeof( ((RVC_tzPGN_BATT_SUMM *)NULL )->teTempSts ) }
};

// Diagnostic Message 1
static const PGN_tzFIELD_DESC XT_FAR azDiagMsg1Fields[] =
{
    { PGN_eTYPE_BIT,   0,   2, (uint16)( (uint32)&( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsProdOn ) ), sizeof( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsProdOn ) },
    { PGN_eTYPE_BIT,   2,   2, (uint16)( (uint32)&( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsProdActive ) ), sizeof( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsProdActive ) },
    { PGN_eTYPE_BIT,   4,   2, (uint16)( (uint32)&( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsYel ) ), sizeof( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsYel ) },
    { PGN_eTYPE_BIT,   6,   2, (uint16)( (uint32)&( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsRed ) ), sizeof( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teOpStsRed ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teProdId ) ), sizeof( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->teProdId ) },
    { PGN_eTYPE_SINT,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->uiExtraCount ) ), sizeof( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->uiExtraCount ) },
    { PGN_eTYPE_POINTER,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->ptzExtra ) ), sizeof( ((RVC_tzPGN_DIAG_MSG1 *)NULL )->ptzExtra ) }
};

static const PGN_tzFIELD_DESC XT_FAR azDiagMsg1ExtraFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucSpnMsb ) ), sizeof( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucSpnMsb ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucSpnIsb ) ), sizeof( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucSpnIsb ) },
    { PGN_eTYPE_BIT,  16,   5, (uint16)( (uint32)&( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->teFmi ) ), sizeof( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->teFmi ) },
    { PGN_eTYPE_BIT,  21,   3, (uint16)( (uint32)&( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucSpnLsb ) ), sizeof( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucSpnLsb ) },
    { PGN_eTYPE_BIT,  24,   7, (uint16)( (uint32)&( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucOccurrenceCnt ) ), sizeof( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucOccurrenceCnt ) },
    { PGN_eTYPE_UCHAR,  32,   1, (uint16)( (uint32)&( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucProdIdExt ) ), sizeof( ((RVC_tzPGN_EXTRA_DIAG_MSG1 *)NULL )->ucProdIdExt ) }
};

// Instance Assignment
static const PGN_tzFIELD_DESC XT_FAR azInstAssignFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_ASSIGN *)NULL )->teDevType ) ), sizeof( ((RVC_tzPGN_INST_ASSIGN *)NULL )->teDevType ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_ASSIGN *)NULL )->ucBaseInst ) ), sizeof( ((RVC_tzPGN_INST_ASSIGN *)NULL )->ucBaseInst ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_ASSIGN *)NULL )->ucMaxInst ) ), sizeof( ((RVC_tzPGN_INST_ASSIGN *)NULL )->ucMaxInst ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_ASSIGN *)NULL )->uiBaseIntAddr ) ), sizeof( ((RVC_tzPGN_INST_ASSIGN *)NULL )->uiBaseIntAddr ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_ASSIGN *)NULL )->uiMaxIntAddr ) ), sizeof( ((RVC_tzPGN_INST_ASSIGN *)NULL )->uiMaxIntAddr ) },
};

// Instance Status
static const PGN_tzFIELD_DESC XT_FAR azInstStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_STS *)NULL )->teDevType ) ), sizeof( ((RVC_tzPGN_INST_STS *)NULL )->teDevType ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_STS *)NULL )->ucBaseInst ) ), sizeof( ((RVC_tzPGN_INST_STS *)NULL )->ucBaseInst ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_STS *)NULL )->ucMaxInst ) ), sizeof( ((RVC_tzPGN_INST_STS *)NULL )->ucMaxInst ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_STS *)NULL )->uiBaseIntAddr ) ), sizeof( ((RVC_tzPGN_INST_STS *)NULL )->uiBaseIntAddr ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_INST_STS *)NULL )->uiMaxIntAddr ) ), sizeof( ((RVC_tzPGN_INST_STS *)NULL )->uiMaxIntAddr ) },
};

// ISO Acknowledgment
static const PGN_tzFIELD_DESC XT_FAR azIsoAckFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ACK *)NULL )->teCtrlByte ) ), sizeof( ((RVC_tzPGN_ISO_ACK *)NULL )->teCtrlByte ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ACK *)NULL )->teGroupFunctionValue ) ), sizeof( ((RVC_tzPGN_ISO_ACK *)NULL )->teGroupFunctionValue ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ACK *)NULL )->ulParmGrpNum ) ), sizeof( ((RVC_tzPGN_ISO_ACK *)NULL )->ulParmGrpNum ) }
};

// ISO Address Claim
static const PGN_tzFIELD_DESC XT_FAR azIsoAddrClaimFields[] =
{
    { PGN_eTYPE_BIT,   0,  21, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ulUniqueNumber ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ulUniqueNumber ) },
    { PGN_eTYPE_BIT,  21,  11, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->uiManufacturerCode ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->uiManufacturerCode ) },
    { PGN_eTYPE_BIT,  32,   3, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceLower ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceLower ) },
    { PGN_eTYPE_BIT,  35,   5, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceUpper ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceUpper ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceFunction ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceFunction ) },
    { PGN_eTYPE_BIT,  48,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucRsvBit ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucRsvBit ) },
    { PGN_eTYPE_BIT,  49,   7, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceClass ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceClass ) },
    { PGN_eTYPE_BIT,  56,   4, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSystemInstance ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSystemInstance ) },
    { PGN_eTYPE_BIT,  60,   3, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->teIndustryGroup ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->teIndustryGroup ) },
    { PGN_eTYPE_BIT,  63,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSelfCfgAddr ) ), sizeof( ((RVC_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSelfCfgAddr ) }
};

// ISO Commanded Address
static const PGN_tzFIELD_DESC XT_FAR azIsoCmdAddrFields[] =
{
    { PGN_eTYPE_BIT,   0,  21, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ulUniqueNumber ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ulUniqueNumber ) },
    { PGN_eTYPE_BIT,  21,  11, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->uiManufacturerCode ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->uiManufacturerCode ) },
    { PGN_eTYPE_BIT,  32,   3, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceLower ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceLower ) },
    { PGN_eTYPE_BIT,  35,   5, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceUpper ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceUpper ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceFunction ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceFunction ) },
    { PGN_eTYPE_BIT,  48,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucRsvBit ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucRsvBit ) },
    { PGN_eTYPE_BIT,  49,   7, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceClass ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceClass ) },
    { PGN_eTYPE_BIT,  56,   4, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucSystemInstance ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucSystemInstance ) },
    { PGN_eTYPE_BIT,  60,   3, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->teIndustryGroup ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->teIndustryGroup ) },
    { PGN_eTYPE_BIT,  63,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucSelfCfgAddr ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->ucSelfCfgAddr ) },
    { PGN_eTYPE_UCHAR,  64,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->tePrefSrcAddr ) ), sizeof( ((RVC_tzPGN_ISO_CMD_ADDR *)NULL )->tePrefSrcAddr ) }
};

// ISO Request
static const PGN_tzFIELD_DESC XT_FAR azIsoReqFields[] =
{
    { PGN_eTYPE_BIT,   0,  24, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_REQ *)NULL )->ulParmGrpNum ) ), sizeof( ((RVC_tzPGN_ISO_REQ *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - Abort
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManAbortFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ucAbortGroupFunctionCode ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ucAbortGroupFunctionCode ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ulParmGrpNum ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - BAM
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManBamFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucBamGroupFunctionCode ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucBamGroupFunctionCode ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->uiTotalMsgSz ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->uiTotalMsgSz ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucTotalNumFramesToBeSent ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucTotalNumFramesToBeSent ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ulParmGrpNum ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - CTS
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManCtsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucCtsGroupFunctionCode ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucCtsGroupFunctionCode ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumFramesThatCanBeSent ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumFramesThatCanBeSent ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumNextFrameToBeSent ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumNextFrameToBeSent ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ulParmGrpNum ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - EOM
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManEomFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucEomGroupFunctionCode ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucEomGroupFunctionCode ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->uiTotalMsgSz ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->uiTotalMsgSz ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucTotalNumFramesRxed ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucTotalNumFramesRxed ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ulParmGrpNum ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - RTS
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManRtsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucRtsGroupFunctionCode ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucRtsGroupFunctionCode ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->uiTotalMsgSz ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->uiTotalMsgSz ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucTotalNumFramesXmit ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucTotalNumFramesXmit ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ulParmGrpNum ) ), sizeof( ((RVC_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Data Transfer
static const PGN_tzFIELD_DESC XT_FAR azIsoTpXferFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_XFER *)NULL )->ucSeqNumMultiPacketFrame ) ), sizeof( ((RVC_tzPGN_ISO_TP_XFER *)NULL )->ucSeqNumMultiPacketFrame ) },
    { PGN_eTYPE_UCHAR,   8,   7, (uint16)( (uint32)&( ((RVC_tzPGN_ISO_TP_XFER *)NULL )->aucMultiPacketPacketizedData ) ), sizeof( ((RVC_tzPGN_ISO_TP_XFER *)NULL )->aucMultiPacketPacketizedData ) }
};

// Product Identification
static const PGN_tzFIELD_DESC XT_FAR azProdIdentFields[] =
{
    { PGN_eTYPE_SINT,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_PROD_IDENT *)NULL )->uiExtraCount ) ), sizeof( ((RVC_tzPGN_PROD_IDENT *)NULL )->uiExtraCount ) },
    { PGN_eTYPE_POINTER,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_PROD_IDENT *)NULL )->ptzExtra ) ), sizeof( ((RVC_tzPGN_PROD_IDENT *)NULL )->ptzExtra ) }
};

static const PGN_tzFIELD_DESC XT_FAR azProdIdentExtraFields[] =
{
    { PGN_eTYPE_SCHAR,   0,   1, (uint16)( (uint32)&( ((RVC_tzPGN_EXTRA_PROD_IDENT *)NULL )->ucData ) ), sizeof( ((RVC_tzPGN_EXTRA_PROD_IDENT *)NULL )->ucData ) }
};

// Solar Controller Solar Array Status
static const PGN_tzFIELD_DESC XT_FAR azSccArrayStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_ARRAY_STS *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_ARRAY_STS *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_ARRAY_STS *)NULL )->uiArrayV ) ), sizeof( ((RVC_tzPGN_SCC_ARRAY_STS *)NULL )->uiArrayV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_ARRAY_STS *)NULL )->uiArrayI ) ), sizeof( ((RVC_tzPGN_SCC_ARRAY_STS *)NULL )->uiArrayI ) }
};

// Solar Controller Battery Status
static const PGN_tzFIELD_DESC XT_FAR azSccBattStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucInst ) },
    { PGN_eTYPE_BIT,   8,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucDcSrcInst ) ), sizeof( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucDcSrcInst ) },
    { PGN_eTYPE_BIT,  16,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucChgPriority ) ), sizeof( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucChgPriority ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->uiBattVolts ) ), sizeof( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->uiBattVolts ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->uiBattCurrent ) ), sizeof( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->uiBattCurrent ) },
    { PGN_eTYPE_UCHAR,  56,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucBattTemp ) ), sizeof( ((RVC_tzPGN_SCC_BATT_STS *)NULL )->ucBattTemp ) }
};

// Solar Controller Configuration Command
static const PGN_tzFIELD_DESC XT_FAR azSccCfgCmdFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->ucInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teChgAlg ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teChgAlg ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teChgMode ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teChgMode ) },
    { PGN_eTYPE_BIT,  24,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teBattSensPres ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teBattSensPres ) },
    { PGN_eTYPE_BIT,  26,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teLinkageMode ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teLinkageMode ) },
    { PGN_eTYPE_BIT,  28,   4, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teBattType ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->teBattType ) },
    { PGN_eTYPE_UINT,  32,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->uiBattBankSz ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->uiBattBankSz ) },
    { PGN_eTYPE_UCHAR,  56,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->ucMaxChgI ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD *)NULL )->ucMaxChgI ) }
};

// Solar Controller Configuration Command 2
static const PGN_tzFIELD_DESC XT_FAR azSccCfgCmd2Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->uiBulkV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->uiBulkV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->uiFloatV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->uiFloatV ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->uiChgRetV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD2 *)NULL )->uiChgRetV ) }
};

// Solar Controller Configuration Command 3
static const PGN_tzFIELD_DESC XT_FAR azSccCfgCmd3Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->uiBattUvWarnThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->uiBattUvWarnThresh ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->uiBattOvSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->uiBattOvSdThresh ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->uiBattUvSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD3 *)NULL )->uiBattUvSdThresh ) }
};

// Solar Controller Configuration Command 4
static const PGN_tzFIELD_DESC XT_FAR azSccCfgCmd4Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->uiBattOvRetV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->uiBattOvRetV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->uiBattUvRetV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->uiBattUvRetV ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucBattUvDly ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucBattUvDly ) },
    { PGN_eTYPE_UCHAR,  48,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucAbsorpTime ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucAbsorpTime ) },
    { PGN_eTYPE_BIT,  56,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucTempCompConst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD4 *)NULL )->ucTempCompConst ) }
};

// Solar Controller Configuration Command 5
static const PGN_tzFIELD_DESC XT_FAR azSccCfgCmd5Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucInst ) },
    { PGN_eTYPE_BIT,   8,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucChgPrio ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucChgPrio ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucExtTempOtSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucExtTempOtSdThresh ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucExtTempUtSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_CMD5 *)NULL )->ucExtTempUtSdThresh ) }
};

// Solar Controller Configuration Status
static const PGN_tzFIELD_DESC XT_FAR azSccCfgStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->ucInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teChgAlg ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teChgAlg ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teChgMode ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teChgMode ) },
    { PGN_eTYPE_BIT,  24,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teBattSensPres ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teBattSensPres ) },
    { PGN_eTYPE_BIT,  26,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teLinkMode ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teLinkMode ) },
    { PGN_eTYPE_BIT,  28,   4, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teBattType ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->teBattType ) },
    { PGN_eTYPE_UINT,  32,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->uiBattBankSz ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->uiBattBankSz ) },
    { PGN_eTYPE_UCHAR,  56,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->ucMaxChgI ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS *)NULL )->ucMaxChgI ) }
};

// Solar Controller Configuration Status 2
static const PGN_tzFIELD_DESC XT_FAR azSccCfgSts2Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->uiBulkV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->uiBulkV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->uiFloatV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->uiFloatV ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->uiChgRetV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS2 *)NULL )->uiChgRetV ) }
};

// Solar Controller Configuration Status 3
static const PGN_tzFIELD_DESC XT_FAR azSccCfgSts3Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->uiBattUvWarnThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->uiBattUvWarnThresh ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->uiBattOvSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->uiBattOvSdThresh ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->uiBattUvSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS3 *)NULL )->uiBattUvSdThresh ) }
};

// Solar Controller Configuration Status 4
static const PGN_tzFIELD_DESC XT_FAR azSccCfgSts4Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->uiBattOvRetV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->uiBattOvRetV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->uiBattUvRetV ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->uiBattUvRetV ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucBattUvDly ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucBattUvDly ) },
    { PGN_eTYPE_UCHAR,  48,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucAbsorpTime ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucAbsorpTime ) },
    { PGN_eTYPE_BIT,  56,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucTempCompConst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS4 *)NULL )->ucTempCompConst ) }
};

// Solar Controller Configuration Status 5
static const PGN_tzFIELD_DESC XT_FAR azSccCfgSts5Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucInst ) },
    { PGN_eTYPE_BIT,   8,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucChgPrio ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucChgPrio ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucExtTempOtSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucExtTempOtSdThresh ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucExtTempUtSdThresh ) ), sizeof( ((RVC_tzPGN_SCC_CFG_STS5 *)NULL )->ucExtTempUtSdThresh ) }
};

// Solar Controller Command
static const PGN_tzFIELD_DESC XT_FAR azSccCmdFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CMD *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_CMD *)NULL )->ucInst ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CMD *)NULL )->teSts ) ), sizeof( ((RVC_tzPGN_SCC_CMD *)NULL )->teSts ) },
    { PGN_eTYPE_BIT,  16,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CMD *)NULL )->teEnableOnPwrUp ) ), sizeof( ((RVC_tzPGN_SCC_CMD *)NULL )->teEnableOnPwrUp ) },
    { PGN_eTYPE_BIT,  18,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CMD *)NULL )->teClrHist ) ), sizeof( ((RVC_tzPGN_SCC_CMD *)NULL )->teClrHist ) },
    { PGN_eTYPE_BIT,  20,   4, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_CMD *)NULL )->teForceChg ) ), sizeof( ((RVC_tzPGN_SCC_CMD *)NULL )->teForceChg ) }
};

// Solar Equalization Configuration Command
static const PGN_tzFIELD_DESC XT_FAR azSccEqlzCfgCmdFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->uiEqlzV ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->uiEqlzV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->uiEqlzTime ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->uiEqlzTime ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->ucEqlzIntvl ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_CMD *)NULL )->ucEqlzIntvl ) }
};

// Solar Equalization Configuration Status
static const PGN_tzFIELD_DESC XT_FAR azSccEqlzCfgStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->uiEqlzV ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->uiEqlzV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->uiEqlzTime ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->uiEqlzTime ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->ucEqlzIntvl ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_CFG_STS *)NULL )->ucEqlzIntvl ) }
};

// Solar Equalization Status
static const PGN_tzFIELD_DESC XT_FAR azSccEqlzStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->uiTimeRemain ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->uiTimeRemain ) },
    { PGN_eTYPE_BIT,  24,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->tePreChgSts ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->tePreChgSts ) },
    { PGN_eTYPE_UCHAR,  32,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->ucTimeSinceEqlz ) ), sizeof( ((RVC_tzPGN_SCC_EQLZ_STS *)NULL )->ucTimeSinceEqlz ) }
};

// Solar Controller Status
static const PGN_tzFIELD_DESC XT_FAR azSccStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->uiChgV ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->uiChgV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->uiChgI ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->uiChgI ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->ucChgIPer ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->ucChgIPer ) },
    { PGN_eTYPE_UCHAR,  48,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->teOpState ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->teOpState ) },
    { PGN_eTYPE_BIT,  56,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->tePwrUpEnDis ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->tePwrUpEnDis ) },
    { PGN_eTYPE_BIT,  58,   2, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->teClrHist ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->teClrHist ) },
    { PGN_eTYPE_BIT,  60,   4, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS *)NULL )->teForceChg ) ), sizeof( ((RVC_tzPGN_SCC_STS *)NULL )->teForceChg ) }
};

// Solar Controller Status 2
static const PGN_tzFIELD_DESC XT_FAR azSccSts2Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS2 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_STS2 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS2 *)NULL )->uiRatedBattV ) ), sizeof( ((RVC_tzPGN_SCC_STS2 *)NULL )->uiRatedBattV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS2 *)NULL )->uiRatedBattI ) ), sizeof( ((RVC_tzPGN_SCC_STS2 *)NULL )->uiRatedBattI ) }
};

// Solar Controller Status 3
static const PGN_tzFIELD_DESC XT_FAR azSccSts3Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS3 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_STS3 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS3 *)NULL )->uiRatedPvV ) ), sizeof( ((RVC_tzPGN_SCC_STS3 *)NULL )->uiRatedPvV ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS3 *)NULL )->uiRatedPvI ) ), sizeof( ((RVC_tzPGN_SCC_STS3 *)NULL )->uiRatedPvI ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS3 *)NULL )->uiRatedPvOverPwr ) ), sizeof( ((RVC_tzPGN_SCC_STS3 *)NULL )->uiRatedPvOverPwr ) }
};

// Solar Controller Status 4
static const PGN_tzFIELD_DESC XT_FAR azSccSts4Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS4 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_STS4 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS4 *)NULL )->uiTodayAh ) ), sizeof( ((RVC_tzPGN_SCC_STS4 *)NULL )->uiTodayAh ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS4 *)NULL )->uiYesterdayAh ) ), sizeof( ((RVC_tzPGN_SCC_STS4 *)NULL )->uiYesterdayAh ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS4 *)NULL )->uiBeforeYesterdayAh ) ), sizeof( ((RVC_tzPGN_SCC_STS4 *)NULL )->uiBeforeYesterdayAh ) }
};

// Solar Controller Status 5
static const PGN_tzFIELD_DESC XT_FAR azSccSts5Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS5 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_STS5 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS5 *)NULL )->uiWeekAh ) ), sizeof( ((RVC_tzPGN_SCC_STS5 *)NULL )->uiWeekAh ) },
    { PGN_eTYPE_ULONG,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS5 *)NULL )->ulCumPwrGen ) ), sizeof( ((RVC_tzPGN_SCC_STS5 *)NULL )->ulCumPwrGen ) }
};

// Solar Controller Status 6
static const PGN_tzFIELD_DESC XT_FAR azSccSts6Fields[] =
{
    { PGN_eTYPE_BIT,   0,   8, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS6 *)NULL )->ucInst ) ), sizeof( ((RVC_tzPGN_SCC_STS6 *)NULL )->ucInst ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS6 *)NULL )->uiOperatingDays ) ), sizeof( ((RVC_tzPGN_SCC_STS6 *)NULL )->uiOperatingDays ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((RVC_tzPGN_SCC_STS6 *)NULL )->uiIntTemp ) ), sizeof( ((RVC_tzPGN_SCC_STS6 *)NULL )->uiIntTemp ) }
};

// Describe the descriptor of each PGN

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescAlarmCmd =
{
        -1,
        6,
        RVC_mRECV_ALARM_CMD,
        NULL,
        RVC_DLC_ALARM_CMD,
        sizeof( RVC_tzPGN_ALARM_CMD ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azAlarmCmdFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescAlarmSts =
{
        -1,
        6,
        NULL,
        RVC_mSEND_ALARM_STS,
        RVC_DLC_ALARM_STS,
        sizeof( RVC_tzPGN_ALARM_STS ),
        11,
        (const PGN_tzFIELD_DESC * XT_FAR) azAlarmStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattCmd =
{
        -1,
        6,
        RVC_mRECV_BATT_CMD,
        NULL,
        RVC_DLC_BATT_CMD,
        sizeof( RVC_tzPGN_BATT_CMD ),
        7,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattCmdFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattSts1 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_BATT_STS1,
        RVC_DLC_BATT_STS1,
        sizeof( RVC_tzPGN_BATT_STS1 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattSts1Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattSts11 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_BATT_STS11,
        RVC_DLC_BATT_STS11,
        sizeof( RVC_tzPGN_BATT_STS11 ),
        8,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattSts11Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattSts2 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_BATT_STS2,
        RVC_DLC_BATT_STS2,
        sizeof( RVC_tzPGN_BATT_STS2 ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattSts2Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattSts3 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_BATT_STS3,
        RVC_DLC_BATT_STS3,
        sizeof( RVC_tzPGN_BATT_STS3 ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattSts3Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattSts4 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_BATT_STS4,
        RVC_DLC_BATT_STS4,
        sizeof( RVC_tzPGN_BATT_STS4 ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattSts4Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattSts6 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_BATT_STS6,
        RVC_DLC_BATT_STS6,
        sizeof( RVC_tzPGN_BATT_STS6 ),
        14,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattSts6Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescBattSumm =
{
        -1,
        6,
        NULL,
        RVC_mSEND_BATT_SUMM,
        RVC_DLC_BATT_SUMM,
        sizeof( RVC_tzPGN_BATT_SUMM ),
        7,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattSummFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescDiagMsg1 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_DIAG_MSG1,
        RVC_DLC_DIAG_MSG1,
        sizeof( RVC_tzPGN_DIAG_MSG1 ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azDiagMsg1Fields,
        RVC_DLC_EXTRA_DIAG_MSG1,
        sizeof( RVC_tzPGN_EXTRA_DIAG_MSG1 ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azDiagMsg1ExtraFields
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescInstAssign =
{
        -1,
        7,
        RVC_mRECV_INST_ASSIGN,
        NULL,
        RVC_DLC_INST_ASSIGN,
        sizeof( RVC_tzPGN_INST_ASSIGN ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azInstAssignFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescInstSts =
{
        -1,
        7,
        RVC_mRECV_INST_STS,
        RVC_mSEND_INST_STS,
        RVC_DLC_INST_STS,
        sizeof( RVC_tzPGN_INST_STS ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azInstStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoAck =
{
        -1,
        6,
        RVC_mRECV_ISO_ACK,
        RVC_mSEND_ISO_ACK,
        RVC_DLC_ISO_ACK,
        sizeof( RVC_tzPGN_ISO_ACK ),
        3,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoAckFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoAddrClaim =
{
        -1,
        6,
        RVC_mRECV_ISO_ADDR_CLAIM,
        RVC_mSEND_ISO_ADDR_CLAIM,
        RVC_DLC_ISO_ADDR_CLAIM,
        sizeof( RVC_tzPGN_ISO_ADDR_CLAIM ),
        10,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoAddrClaimFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoCmdAddr =
{
        -1,
        6,
        RVC_mRECV_ISO_CMD_ADDR,
        NULL,
        RVC_DLC_ISO_CMD_ADDR,
        sizeof( RVC_tzPGN_ISO_CMD_ADDR ),
        11,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoCmdAddrFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoReq =
{
        -1,
        6,
        RVC_mRECV_ISO_REQ,
        RVC_mSEND_ISO_REQ,
        RVC_DLC_ISO_REQ,
        sizeof( RVC_tzPGN_ISO_REQ ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoReqFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoTpConnManAbort =
{
        0,
        7,
        RVC_mRECV_ISO_TP_CONN_MAN_ABORT,
        RVC_mSEND_ISO_TP_CONN_MAN_ABORT,
        RVC_DLC_ISO_TP_CONN_MAN_ABORT,
        sizeof( RVC_tzPGN_ISO_TP_CONN_MAN_ABORT ),
        2,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManAbortFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoTpConnManBam =
{
        0,
        7,
        RVC_mRECV_ISO_TP_CONN_MAN_BAM,
        RVC_mSEND_ISO_TP_CONN_MAN_BAM,
        RVC_DLC_ISO_TP_CONN_MAN_BAM,
        sizeof( RVC_tzPGN_ISO_TP_CONN_MAN_BAM ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManBamFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoTpConnManCts =
{
        0,
        7,
        RVC_mRECV_ISO_TP_CONN_MAN_CTS,
        RVC_mSEND_ISO_TP_CONN_MAN_CTS,
        RVC_DLC_ISO_TP_CONN_MAN_CTS,
        sizeof( RVC_tzPGN_ISO_TP_CONN_MAN_CTS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManCtsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoTpConnManEom =
{
        0,
        7,
        RVC_mRECV_ISO_TP_CONN_MAN_EOM,
        RVC_mSEND_ISO_TP_CONN_MAN_EOM,
        RVC_DLC_ISO_TP_CONN_MAN_EOM,
        sizeof( RVC_tzPGN_ISO_TP_CONN_MAN_EOM ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManEomFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoTpConnManRts =
{
        0,
        7,
        RVC_mRECV_ISO_TP_CONN_MAN_RTS,
        RVC_mSEND_ISO_TP_CONN_MAN_RTS,
        RVC_DLC_ISO_TP_CONN_MAN_RTS,
        sizeof( RVC_tzPGN_ISO_TP_CONN_MAN_RTS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManRtsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescIsoTpXfer =
{
        -1,
        7,
        RVC_mRECV_ISO_TP_XFER,
        RVC_mSEND_ISO_TP_XFER,
        RVC_DLC_ISO_TP_XFER,
        sizeof( RVC_tzPGN_ISO_TP_XFER ),
        2,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpXferFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescProdIdent =
{
        -1,
        6,
        RVC_mRECV_PROD_IDENT,
        RVC_mSEND_PROD_IDENT,
        RVC_DLC_PROD_IDENT,
        sizeof( RVC_tzPGN_PROD_IDENT ),
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) azProdIdentFields,
        RVC_DLC_EXTRA_PROD_IDENT,
        sizeof( RVC_tzPGN_EXTRA_PROD_IDENT ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azProdIdentExtraFields
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccArraySts =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_ARRAY_STS,
        RVC_DLC_SCC_ARRAY_STS,
        sizeof( RVC_tzPGN_SCC_ARRAY_STS ),
        3,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccArrayStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccBattSts =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_BATT_STS,
        RVC_DLC_SCC_BATT_STS,
        sizeof( RVC_tzPGN_SCC_BATT_STS ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccBattStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgCmd =
{
        -1,
        6,
        RVC_mRECV_SCC_CFG_CMD,
        NULL,
        RVC_DLC_SCC_CFG_CMD,
        sizeof( RVC_tzPGN_SCC_CFG_CMD ),
        8,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgCmdFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgCmd2 =
{
        -1,
        6,
        RVC_mRECV_SCC_CFG_CMD2,
        NULL,
        RVC_DLC_SCC_CFG_CMD2,
        sizeof( RVC_tzPGN_SCC_CFG_CMD2 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgCmd2Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgCmd3 =
{
        -1,
        6,
        RVC_mRECV_SCC_CFG_CMD3,
        NULL,
        RVC_DLC_SCC_CFG_CMD3,
        sizeof( RVC_tzPGN_SCC_CFG_CMD3 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgCmd3Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgCmd4 =
{
        -1,
        6,
        RVC_mRECV_SCC_CFG_CMD4,
        NULL,
        RVC_DLC_SCC_CFG_CMD4,
        sizeof( RVC_tzPGN_SCC_CFG_CMD4 ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgCmd4Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgCmd5 =
{
        -1,
        6,
        RVC_mRECV_SCC_CFG_CMD5,
        NULL,
        RVC_DLC_SCC_CFG_CMD5,
        sizeof( RVC_tzPGN_SCC_CFG_CMD5 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgCmd5Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgSts =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_CFG_STS,
        RVC_DLC_SCC_CFG_STS,
        sizeof( RVC_tzPGN_SCC_CFG_STS ),
        8,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgSts2 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_CFG_STS2,
        RVC_DLC_SCC_CFG_STS2,
        sizeof( RVC_tzPGN_SCC_CFG_STS2 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgSts2Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgSts3 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_CFG_STS3,
        RVC_DLC_SCC_CFG_STS3,
        sizeof( RVC_tzPGN_SCC_CFG_STS3 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgSts3Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgSts4 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_CFG_STS4,
        RVC_DLC_SCC_CFG_STS4,
        sizeof( RVC_tzPGN_SCC_CFG_STS4 ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgSts4Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCfgSts5 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_CFG_STS5,
        RVC_DLC_SCC_CFG_STS5,
        sizeof( RVC_tzPGN_SCC_CFG_STS5 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCfgSts5Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccCmd =
{
        -1,
        6,
        RVC_mRECV_SCC_CMD,
        NULL,
        RVC_DLC_SCC_CMD,
        sizeof( RVC_tzPGN_SCC_CMD ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccCmdFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccEqlzCfgCmd =
{
        -1,
        6,
        RVC_mRECV_SCC_EQLZ_CFG_CMD,
        NULL,
        RVC_DLC_SCC_EQLZ_CFG_CMD,
        sizeof( RVC_tzPGN_SCC_EQLZ_CFG_CMD ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccEqlzCfgCmdFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccEqlzCfgSts =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_EQLZ_CFG_STS,
        RVC_DLC_SCC_EQLZ_CFG_STS,
        sizeof( RVC_tzPGN_SCC_EQLZ_CFG_STS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccEqlzCfgStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccEqlzSts =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_EQLZ_STS,
        RVC_DLC_SCC_EQLZ_STS,
        sizeof( RVC_tzPGN_SCC_EQLZ_STS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccEqlzStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccSts =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_STS,
        RVC_DLC_SCC_STS,
        sizeof( RVC_tzPGN_SCC_STS ),
        8,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccSts2 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_STS2,
        RVC_DLC_SCC_STS2,
        sizeof( RVC_tzPGN_SCC_STS2 ),
        3,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccSts2Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccSts3 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_STS3,
        RVC_DLC_SCC_STS3,
        sizeof( RVC_tzPGN_SCC_STS3 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccSts3Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccSts4 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_STS4,
        RVC_DLC_SCC_STS4,
        sizeof( RVC_tzPGN_SCC_STS4 ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccSts4Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccSts5 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_STS5,
        RVC_DLC_SCC_STS5,
        sizeof( RVC_tzPGN_SCC_STS5 ),
        3,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccSts5Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR RVC_tzDescSccSts6 =
{
        -1,
        6,
        NULL,
        RVC_mSEND_SCC_STS6,
        RVC_DLC_SCC_STS6,
        sizeof( RVC_tzPGN_SCC_STS6 ),
        3,
        (const PGN_tzFIELD_DESC * XT_FAR) azSccSts6Fields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

#if !defined( WIN32 ) && !defined(__TMS320C2000__)
#pragma CONST_SEG DEFAULT
#endif

// List of receivable PGNs
const uint32 XB_kaulRX_PGN_LIST[] = 
{
	RVC_PGN_ISO_ACK,
	RVC_PGN_ISO_REQ,
	RVC_PGN_ISO_TP_XFER,
	RVC_PGN_ISO_TP_CONN_MAN,
	RVC_PGN_ISO_ADDR_CLAIM,
	RVC_PGN_ISO_CMD_ADDR,
	RVC_PGN_PROD_IDENT,
	RVC_PGN_INST_STS,
	RVC_PGN_INST_ASSIGN,
	RVC_PGN_SCC_CFG_CMD5,
	RVC_PGN_SCC_CFG_CMD4,
	RVC_PGN_SCC_CFG_CMD3,
	RVC_PGN_SCC_CFG_CMD2,
	RVC_PGN_BATT_CMD,
	RVC_PGN_ALARM_CMD,
	RVC_PGN_SCC_EQLZ_CFG_CMD,
	RVC_PGN_SCC_CFG_CMD,
	RVC_PGN_SCC_CMD,
};

uint16 XBPGNTBL_fnSizeOfRxPgnList( void )
{
    return ( XT_mDIM( XB_kaulRX_PGN_LIST ) );
}

// List of Transmittable PGNs
const uint32 XB_kaulTX_PGN_LIST[] = 
{
	RVC_PGN_ISO_ACK,
	RVC_PGN_ISO_REQ,
	RVC_PGN_ISO_TP_XFER,
	RVC_PGN_ISO_TP_CONN_MAN,
	RVC_PGN_ISO_ADDR_CLAIM,
	RVC_PGN_PROD_IDENT,
	RVC_PGN_INST_STS,
	RVC_PGN_SCC_CFG_STS5,
	RVC_PGN_BATT_SUMM,
	RVC_PGN_SCC_CFG_STS4,
	RVC_PGN_SCC_CFG_STS3,
	RVC_PGN_SCC_CFG_STS2,
	RVC_PGN_SCC_ARRAY_STS,
	RVC_PGN_SCC_BATT_STS,
	RVC_PGN_SCC_STS6,
	RVC_PGN_SCC_STS5,
	RVC_PGN_SCC_STS4,
	RVC_PGN_SCC_STS3,
	RVC_PGN_SCC_STS2,
	RVC_PGN_BATT_STS11,
	RVC_PGN_BATT_STS6,
	RVC_PGN_BATT_STS4,
	RVC_PGN_BATT_STS3,
	RVC_PGN_BATT_STS2,
	RVC_PGN_BATT_STS1,
	RVC_PGN_ALARM_STS,
	RVC_PGN_SCC_EQLZ_CFG_STS,
	RVC_PGN_SCC_EQLZ_STS,
	RVC_PGN_SCC_CFG_STS,
	RVC_PGN_SCC_STS,
	RVC_PGN_DIAG_MSG1,
};

uint16 XBPGNTBL_fnSizeOfTxPgnList( void )
{
    return ( XT_mDIM( XB_kaulTX_PGN_LIST ) );
}

// List mnemonics for all PGNs used by RVC_SCC
const char * XB_kapcPgnMnemonics[] =
{
    "IsoAck",
    "IsoReq",
    "IsoTpXfer",
    "IsoTpConnManRts",
    "IsoTpConnManCts",
    "IsoTpConnManEom",
    "IsoTpConnManBam",
    "IsoTpConnManAbort",
    "IsoAddrClaim",
    "IsoCmdAddr",
    "ProdIdent",
    "InstSts",
    "InstAssign",
    "SccCfgCmd5",
    "SccCfgSts5",
    "BattSumm",
    "SccCfgCmd4",
    "SccCfgSts4",
    "SccCfgCmd3",
    "SccCfgSts3",
    "SccCfgCmd2",
    "SccCfgSts2",
    "SccArraySts",
    "SccBattSts",
    "SccSts6",
    "SccSts5",
    "SccSts4",
    "SccSts3",
    "SccSts2",
    "BattCmd",
    "BattSts11",
    "BattSts6",
    "BattSts4",
    "BattSts3",
    "BattSts2",
    "BattSts1",
    "AlarmCmd",
    "AlarmSts",
    "SccEqlzCfgCmd",
    "SccEqlzCfgSts",
    "SccEqlzSts",
    "SccCfgCmd",
    "SccCmd",
    "SccCfgSts",
    "SccSts",
    "DiagMsg1",
};

// List of all PGNS with descriptors for those used by RVC_SCC
const PGN_tzPGN_INFO XB_katzALL_PGN_LIST[] =
{
    { RVC_PGN_ISO_ACK,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_ACK,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoAck },

    { RVC_PGN_ISO_REQ,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_REQ,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoReq },

    { RVC_PGN_ISO_TP_XFER,              -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoTpXfer },

    { RVC_PGN_ISO_TP_CONN_MAN,          16,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoTpConnManRts },

    { RVC_PGN_ISO_TP_CONN_MAN,          17,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoTpConnManCts },

    { RVC_PGN_ISO_TP_CONN_MAN,          19,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoTpConnManEom },

    { RVC_PGN_ISO_TP_CONN_MAN,          32,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoTpConnManBam },

    { RVC_PGN_ISO_TP_CONN_MAN,         255,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoTpConnManAbort },

    { RVC_PGN_ISO_ADDR_CLAIM,           -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoAddrClaim },

    { RVC_PGN_ISO_CMD_ADDR,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescIsoCmdAddr },

    { RVC_PGN_PROD_IDENT,               -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescProdIdent },

    { RVC_PGN_INST_STS,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescInstSts },

    { RVC_PGN_INST_ASSIGN,              -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescInstAssign },

    { RVC_PGN_SCC_CFG_CMD5,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgCmd5 },

    { RVC_PGN_SCC_CFG_STS5,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgSts5 },

    { RVC_PGN_BATT_SUMM,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattSumm },

    { RVC_PGN_SCC_CFG_CMD4,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgCmd4 },

    { RVC_PGN_SCC_CFG_STS4,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgSts4 },

    { RVC_PGN_SCC_CFG_CMD3,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgCmd3 },

    { RVC_PGN_SCC_CFG_STS3,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgSts3 },

    { RVC_PGN_SCC_CFG_CMD2,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgCmd2 },

    { RVC_PGN_SCC_CFG_STS2,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgSts2 },

    { RVC_PGN_SCC_ARRAY_STS,            -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccArraySts },

    { RVC_PGN_SCC_BATT_STS,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccBattSts },

    { RVC_PGN_SCC_STS6,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccSts6 },

    { RVC_PGN_SCC_STS5,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccSts5 },

    { RVC_PGN_SCC_STS4,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccSts4 },

    { RVC_PGN_SCC_STS3,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccSts3 },

    { RVC_PGN_SCC_STS2,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccSts2 },

    { RVC_PGN_BATT_CMD,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattCmd },

    { RVC_PGN_BATT_STS11,               -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattSts11 },

    { RVC_PGN_BATT_STS6,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattSts6 },

    { RVC_PGN_BATT_STS4,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattSts4 },

    { RVC_PGN_BATT_STS3,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattSts3 },

    { RVC_PGN_BATT_STS2,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattSts2 },

    { RVC_PGN_BATT_STS1,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescBattSts1 },

    { RVC_PGN_ALARM_CMD,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescAlarmCmd },

    { RVC_PGN_ALARM_STS,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescAlarmSts },

    { RVC_PGN_SCC_EQLZ_CFG_CMD,         -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccEqlzCfgCmd },

    { RVC_PGN_SCC_EQLZ_CFG_STS,         -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccEqlzCfgSts },

    { RVC_PGN_SCC_EQLZ_STS,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccEqlzSts },

    { RVC_PGN_SCC_CFG_CMD,              -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgCmd },

    { RVC_PGN_SCC_CMD,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX,
        PGN_PG_TYPE_CMD,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCmd },

    { RVC_PGN_SCC_CFG_STS,              -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccCfgSts },

    { RVC_PGN_SCC_STS,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescSccSts },

    { RVC_PGN_DIAG_MSG1,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( PGN_tzPGN_DESC * XT_FAR) &RVC_tzDescDiagMsg1 },

};

uint16 XBPGNTBL_fnSizeOfAllPgnList( void )
{
    return ( XT_mDIM( XB_katzALL_PGN_LIST ) );
}

// Number of entries in dynamic support arrays rounded up to byte boundary
#define   XB_DYNAMIC_COUNT    ( ( XT_mDIM( XB_katzALL_PGN_LIST ) + XT_BITS_PER_BYTE - 1 ) / XT_BITS_PER_BYTE )

uchar8 XB_aucDynamicRx[ XB_DYNAMIC_COUNT ];

uint16 XBPGNTBL_fnSizeOfDynRxLists( void )
{
    return ( XT_mDIM( XB_aucDynamicRx ) );
}

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
