/******************************************************************************

  (c) 2003 - 2024 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup apprxtx apprxtx
  @{

    @brief 
      Macro definitions used by the RV-C application receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef APPRXTX_H
#define APPRXTX_H

#include "xbudefs.h"
#include "xbgdefs.h"
#include "xbwincb.h"

//! All receivable DGNs are procesed by the same handler
//! The DGNs below ar elisted in the same order as in the rvcudefs.h module
//! to make it easier to detect missing handlers when new DGNs are added
#define RVC_mRECV_AC_FLT_CTRL_CFG_CMD1          XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AC_FLT_CTRL_CFG_CMD2          XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AC_FLT_CTRL_CFG_STS1          XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AC_FLT_CTRL_CFG_STS2          XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_CMD_AMB_TEMP         XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_CMD_DC_I             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_CMD_DC_SOC           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_CMD_DC_V             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_CMD_XFER_AC_V        XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_STS_AMB_TEMP         XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_STS_DC_I             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_STS_DC_SOC           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_STS_DC_V             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_AGS_CRIT_STS_XFER_AC_V        XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_ALARM_CMD                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_ALARM_STS                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_CMD                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_STS1                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_STS11                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_STS2                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_STS3                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_STS4                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_STS6                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_BATT_SUMM                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_FLT_CFG_CMD1           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_FLT_CFG_CMD2           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_FLT_CFG_STS1           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_FLT_CFG_STS2           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_STS1                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_STS2                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_STS3                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_AC_STS4                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_CMD1                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_CMD2                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_CMD3                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_CMD4                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_STS1                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_STS2                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_STS3                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CFG_STS4                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_CMD                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_EQLZ_CFG_CMD              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_EQLZ_CFG_STS              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_EQLZ_STS                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_STATS_STS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_STS                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_STS2                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_CHG_STS3                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_COMM_STS1                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_COMM_STS2                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_COMM_STS3                     XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_CFG_CMD3               XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_CMD                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_CONN_STS               XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_STS1                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_STS11                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_STS2                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_STS3                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_STS4                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_DC_SRC_STS6                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_FILE_DNLD_STS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_CMD                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_DEMAND_CMD                XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_DEMAND_STS                XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_RST                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_START_CFG_CMD             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_START_CFG_STS             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_STS1                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_GEN_STS2                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INST_ASSIGN                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INST_STS                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_AC_FLT_CFG_CMD1           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_AC_FLT_CFG_STS1           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_AC_STS1                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_AC_STS2                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_AC_STS3                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_AC_STS4                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_APS_STS                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_CMD1                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_CMD2                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_CMD3                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_CMD4                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_STS1                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_STS2                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_STS3                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CFG_STS4                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_CMD                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_DC_STS                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_HV_DC_BUS_STS             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_OPS_STS                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_STATS_STS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_STS                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_TEMP_STS                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_INV_TEMP_STS2                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_ISO_ACK                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_AC_STS_RMS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_AC_XFER_SW_STS             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_ASSOC_CFG                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_ASSOC_STS                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_CHG_STS                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_DEV_MD_CFG                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_DEV_MD_STS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_FXCC_CFG_CMD               XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_FXCC_CFG_STS               XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_GET_CONFIG_PARAM           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_GET_STATUS_PARAM           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_INV_CTRL_CMD               XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_INV_LD_SH_STS              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_INV_STS                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_LITHIONICS_CMD             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_LITHIONICS_STS             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_PPN_NAK_RSP                XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_PPN_READ_CMD               XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_PPN_READ_RSP               XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_PPN_SESSION_CMD            XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_PPN_SESSION_RSP            XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_PPN_WRITE_CMD              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_PPN_WRITE_RSP              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_REQ                        XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_RPC_CMD                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_SET_CONFIG_PARAM           XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PM_SW_VER_STS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PROD_IDENT                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_PROD_INFO_STS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_ARRAY_STS                 XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_BATT_STS                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_CMD                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_CMD2                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_CMD3                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_CMD4                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_CMD5                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_STS                   XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_STS2                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_STS3                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_STS4                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CFG_STS5                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_CMD                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_EQLZ_CFG_CMD              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_EQLZ_CFG_STS              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_EQLZ_STS                  XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_STS                       XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_STS2                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_STS3                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_STS4                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_STS5                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SCC_STS6                      XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SET_SYS_DATE_TIME             XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SIMPLE_CALIB_CFG              XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SW_VER_STS                    XBWIN_fnRecvGeneralMsg
#define RVC_mRECV_SYS_DATE_TIME_STS             XBWIN_fnRecvGeneralMsg

//! Transmit handler(s)
#define RVC_mSEND_DIAG_MSG1                     XBWIN_fnWantDiagMsg1

#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
