/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup apprxtx apprxtx
  @{

    @brief 
      Macro definitions used by the XanBus application
      receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef APPRXTX_H
#define APPRXTX_H

#define XB_mRX_CHECK                        NULL
#define XB_mRX_HANDLER                      NULL

#define XB_mSEND_ACTIVE_FAULT_STS2          NULL

#define XB_mSEND_ACTIVE_WARN_STS2           NULL

#define XB_mRECV_ASSOC_CFG                  NULL
#define XB_mSEND_ASSOC_CFG                  NULL

#define XB_mRECV_ASSOC_STS                  NULL
#define XB_mSEND_ASSOC_STS                  NULL

#define XB_mRECV_BATT_STS2                  NULL
#define XB_mSEND_BATT_STS2                  NULL

#define XB_mRECV_BMS_STS                    NULL

#define XB_mRECV_CFG                        NULL
#define XB_mSEND_CFG                        NULL

#define XB_mRECV_CHG_CFG                    NULL
#define XB_mSEND_CHG_CFG                    NULL

#define XB_mRECV_CHG_CFG_ABSORP             NULL
#define XB_mSEND_CHG_CFG_ABSORP             NULL

#define XB_mRECV_CHG_CFG_BULK               NULL
#define XB_mSEND_CHG_CFG_BULK               NULL

#define XB_mRECV_CHG_CFG_EQUALIZE           NULL
#define XB_mSEND_CHG_CFG_EQUALIZE           NULL

#define XB_mRECV_CHG_CFG_FLOAT              NULL
#define XB_mSEND_CHG_CFG_FLOAT              NULL

#define XB_mRECV_CHG_CTRL_CMD2              NULL

#define XB_mRECV_CHG_STATS_BATT2            NULL
#define XB_mSEND_CHG_STATS_BATT2            NULL

#define XB_mRECV_CHG_STS                    NULL
#define XB_mSEND_CHG_STS                    NULL

#define XB_mRECV_CLEAR_CMD                  NULL

#define XB_mRECV_COMPLEX_REQ                NULL

#define XB_mRECV_CTRL_CMD                   NULL

#define XB_mRECV_CV_CI_CTRL_CMD             NULL

#define XB_mRECV_DATE_TIME_STS              NULL

#define XB_mRECV_DC_SRC_CFG_BATT            NULL
#define XB_mSEND_DC_SRC_CFG_BATT            NULL

#define XB_mRECV_DC_SRC_CFG_OV              NULL
#define XB_mSEND_DC_SRC_CFG_OV              NULL

#define XB_mRECV_DC_SRC_CFG_PV_ARRAY2       NULL
#define XB_mSEND_DC_SRC_CFG_PV_ARRAY2       NULL

#define XB_mRECV_DC_SRC_CFG_UV              NULL
#define XB_mSEND_DC_SRC_CFG_UV              NULL

#define XB_mRECV_DC_SRC_STS2                NULL
#define XB_mSEND_DC_SRC_STS2                NULL

#define XB_mRECV_DEBUG_FP                   NULL
#define XB_mSEND_DEBUG_FP                   NULL

#define XB_mRECV_DEV_PEEK_ADDR_REQ          NULL

#define XB_mSEND_DEV_PEEK_ADDR_RSP          NULL

#define XB_mRECV_DEV_POKE_ADDR              NULL

#define XB_mRECV_DIAG_MFG_CFG               NULL
#define XB_mSEND_DIAG_MFG_CFG               NULL

#define XB_mRECV_EN_DIS_CFG                 NULL
#define XB_mSEND_EN_DIS_CFG                 NULL

#define XB_mRECV_EXT_TEMP_CFG_OT            NULL
#define XB_mSEND_EXT_TEMP_CFG_OT            NULL

#define XB_mRECV_EXT_TEMP_CFG_UT            NULL
#define XB_mSEND_EXT_TEMP_CFG_UT            NULL

#define XB_mSEND_FAN_STATS                  NULL

#define XB_mSEND_FAN_STS                    NULL

#define XB_mSEND_FAULT_LOG_STS2             NULL

#define XB_mRECV_FEATURE_EN_DIS_CFG         NULL
#define XB_mSEND_FEATURE_EN_DIS_CFG         NULL

#define XB_mRECV_GO_CFG_YOURSELF_CMD        NULL

#define XB_mSEND_HW_REV_STS                 NULL

#define XB_mRECV_INT_TEMP_CFG_OT            NULL
#define XB_mSEND_INT_TEMP_CFG_OT            NULL

#define XB_mRECV_INT_TEMP_CFG_UT            NULL
#define XB_mSEND_INT_TEMP_CFG_UT            NULL

#define XB_mSEND_INT_TEMP_STS               NULL

#define XB_mSEND_ISO_ACK                    NULL

#define XB_mSEND_MPPT_STS                   NULL

#define XB_mSEND_PID_CFG                    NULL

#define XB_mSEND_PID_STS                    NULL

#define XB_mSEND_PROD_INFO_STS              NULL

#define XB_mRECV_RESET_CMD                  NULL

#define XB_mRECV_SIMPLE_CALIB_CFG           NULL
#define XB_mSEND_SIMPLE_CALIB_CFG           NULL

#define XB_mRECV_SPS_CFG                    NULL
#define XB_mSEND_SPS_CFG                    NULL

#define XB_mRECV_SPS_CFG_BATT_SOC           NULL
#define XB_mSEND_SPS_CFG_BATT_SOC           NULL

#define XB_mRECV_SPS_CFG_TRIG               NULL
#define XB_mSEND_SPS_CFG_TRIG               NULL

#define XB_mRECV_SPS_CTRL_CMD               NULL

#define XB_mSEND_SPS_STS                    NULL

#define XB_mSEND_STATE_EVT_LOG_STS          NULL

#define XB_mSEND_STATE_EVT_LOG_STS2         NULL

#define XB_mRECV_STRING_CFG                 NULL
#define XB_mSEND_STRING_CFG                 NULL

#define XB_mSEND_STS                        NULL

#define XB_mSEND_SW_VER_STS                 NULL

#define XB_mRECV_SYS_ID_CFG                 NULL
#define XB_mSEND_SYS_ID_CFG                 NULL

#define XB_mRECV_SYS_ID_STS                 NULL
#define XB_mSEND_SYS_ID_STS                 NULL

#define XB_mSEND_WARN_LOG_STS2              NULL


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
