/*=============================================================================
Copyright 2003 Xantrex International.  All rights reserved.

This source file is proprietary to Xantrex International. and protected by 
copyright. The reproduction, in whole or in part, by anyone without the written 
approval of Xantrex is prohibited.

FILE NAME:  apprxtx.h

PURPOSE:
   
   This file contains the macros for the receive and send
   handlers for the PGNs used by the application.
   
FUNCTION(S):
   None

NOTES:

   While this file is autogenerated... it can not be used as such.
   Rather the contents of this file must be merged with the file used 
   by your project.

CHANGE HISTORY:

Date: Jan-26-2005  by: xanbus_headergen.py
   - Autogenerated

$Log: $

=============================================================================*/

#ifndef APPRXTX_H
#define APPRXTX_H

#include "xbgdefs.h"            // for XBMSG_fnRawReceive
#include "testmsgs.h"           // Test message handlers prototypes

#define XB_mRX_HANDLER                      XBMSG_fnRawReceive

#define XB_mRECV_ISO_ACK                    TESTMSGS_fnRecvIsoAck
#define XB_mSEND_ISO_ACK                    NULL

#define XB_mRECV_DC_SRC_CFG_UV              NULL
#define XB_mSEND_DC_SRC_CFG_UV              NULL

#define XB_mRECV_DC_SRC_CFG_OV              NULL
#define XB_mSEND_DC_SRC_CFG_OV              NULL

#define XB_mRECV_DC_SRC_CFG_UI              NULL
#define XB_mSEND_DC_SRC_CFG_UI              NULL

#define XB_mRECV_DC_SRC_CFG_OI              NULL
#define XB_mSEND_DC_SRC_CFG_OI              NULL

#define XB_mRECV_DC_SRC_CFG_RIP_OV_PEAK     NULL
#define XB_mSEND_DC_SRC_CFG_RIP_OV_PEAK     NULL

#define XB_mRECV_AC_OUT_CFG                 NULL
#define XB_mSEND_AC_OUT_CFG                 NULL

#define XB_mRECV_APS_CFG_UV                 NULL
#define XB_mSEND_APS_CFG_UV                 NULL

#define XB_mRECV_APS_CFG_OV                 NULL
#define XB_mSEND_APS_CFG_OV                 NULL

#define XB_mRECV_OPS_CFG_UV                 NULL
#define XB_mSEND_OPS_CFG_UV                 NULL

#define XB_mRECV_OPS_CFG_OV                 NULL
#define XB_mSEND_OPS_CFG_OV                 NULL

#define XB_mRECV_HV_DC_BUS_CFG_UV           NULL
#define XB_mSEND_HV_DC_BUS_CFG_UV           NULL

#define XB_mRECV_HV_DC_BUS_CFG_OV           NULL
#define XB_mSEND_HV_DC_BUS_CFG_OV           NULL

#define XB_mRECV_EXT_TEMP_CFG_UT            NULL
#define XB_mSEND_EXT_TEMP_CFG_UT            NULL

#define XB_mRECV_EXT_TEMP_CFG_OT            NULL
#define XB_mSEND_EXT_TEMP_CFG_OT            NULL

#define XB_mRECV_INT_TEMP_CFG_UT            NULL
#define XB_mSEND_INT_TEMP_CFG_UT            NULL

#define XB_mRECV_INT_TEMP_CFG_OT            NULL
#define XB_mSEND_INT_TEMP_CFG_OT            NULL

#define XB_mRECV_DC_SRC_CFG_BATT            NULL
#define XB_mSEND_DC_SRC_CFG_BATT            NULL

#define XB_mRECV_CALIB_CMD                  NULL

#define XB_mRECV_INV_CFG_LOAD_SENSE         NULL
#define XB_mSEND_INV_CFG_LOAD_SENSE         NULL

#define XB_mRECV_INV_CFG                    NULL
#define XB_mSEND_INV_CFG                    NULL

#define XB_mRECV_SYS_ID_CFG                 NULL
#define XB_mSEND_SYS_ID_CFG                 NULL

#define XB_mRECV_RESET_CMD                  TESTMSGS_fnRecvResetCmd

#define XB_mRECV_ASSOC_CFG                  NULL
#define XB_mSEND_ASSOC_CFG                  NULL

#define XB_mRECV_CLEAR_CMD                  NULL

#define XB_mRECV_DEV_PEEK_ADDR_REQ          NULL

#define XB_mSEND_DEV_PEEK_ADDR_RSP          NULL

#define XB_mRECV_DEV_POKE_ADDR              NULL

#define XB_mRECV_EN_DIS_CFG                 NULL
#define XB_mSEND_EN_DIS_CFG                 NULL

#define XB_mRECV_ASSOC_STS                  NULL
#define XB_mSEND_ASSOC_STS                  NULL

#define XB_mRECV_INV_CTRL_CMD               NULL

#define XB_mRECV_CTRL_CMD                   NULL

#define XB_mRECV_CFG                        TESTMSGS_fnRecvCfg
#define XB_mSEND_CFG                        NULL

#define XB_mRECV_DIAG_INDIC_CMD             NULL

#define XB_mRECV_DIAG_CNTCT_CMD             NULL

#define XB_mSEND_DIAG_CNTCT_STS             NULL

#define XB_mRECV_DIAG_FAN_CMD               NULL

#define XB_mRECV_DIAG_MFG_CFG               NULL
#define XB_mSEND_DIAG_MFG_CFG               NULL

#define XB_mRECV_AC_OUT_CFG_OV_RMS          NULL
#define XB_mSEND_AC_OUT_CFG_OV_RMS          NULL

#define XB_mRECV_AC_OUT_CFG_UV_RMS          NULL
#define XB_mSEND_AC_OUT_CFG_UV_RMS          NULL

#define XB_mRECV_DC_SRC_CFG_PV_ARRAY        NULL
#define XB_mSEND_DC_SRC_CFG_PV_ARRAY        NULL

#define XB_mRECV_DC_SRC_STS                 TESTMSGS_fnRecvDcSrcSts
#define XB_mSEND_DC_SRC_STS                 TESTMSGS_fnWantDcSrcSts

#define XB_mRECV_AC_OUT_STS_RMS             NULL
#define XB_mSEND_AC_OUT_STS_RMS             NULL

#define XB_mRECV_AC_OUT_STS_PEAK            NULL
#define XB_mSEND_AC_OUT_STS_PEAK            NULL

#define XB_mRECV_AC_OUT_STS_AVG             NULL
#define XB_mSEND_AC_OUT_STS_AVG             NULL

#define XB_mRECV_APS_STS                    NULL
#define XB_mSEND_APS_STS                    NULL

#define XB_mRECV_OPS_STS                    NULL
#define XB_mSEND_OPS_STS                    NULL

#define XB_mRECV_HV_DC_BUS_STS              NULL
#define XB_mSEND_HV_DC_BUS_STS              NULL

#define XB_mRECV_EXT_TEMP_STS               NULL
#define XB_mSEND_EXT_TEMP_STS               NULL

#define XB_mRECV_INT_TEMP_STS               NULL
#define XB_mSEND_INT_TEMP_STS               NULL

#define XB_mRECV_CHG_STS                    NULL

#define XB_mRECV_STS                        NULL
#define XB_mSEND_STS                        NULL

#define XB_mRECV_INV_STATS_AC               NULL
#define XB_mSEND_INV_STATS_AC               NULL

#define XB_mRECV_AGS_STS                    NULL

#define XB_mSEND_SYS_ID_STS                 NULL

#define XB_mSEND_FAULT_LOG_STS              NULL

#define XB_mSEND_PROD_INFO_STS              NULL

#define XB_mRECV_INV_STS                    NULL
#define XB_mSEND_INV_STS                    NULL

#define XB_mRECV_BATT_MON_STS               NULL

#define XB_mRECV_UI_STS                     NULL

#define XB_mSEND_INV_STATS_DC               NULL

#define XB_mSEND_INV_STATS_INT_TEMP         NULL

#define XB_mSEND_INV_STATS_EXT_TEMP         NULL

#define XB_mRECV_GW_STS                     NULL

#define XB_mRECV_CALIB_DATA_STS             NULL
#define XB_mSEND_CALIB_DATA_STS             NULL

#define XB_mRECV_DATE_TIME_STS              TESTMSGS_fnRecvDateTimeSts

#define XB_mSEND_ACTIVE_FAULTS_STS          NULL

#define XB_mSEND_WARN_LOG_STS               NULL

#define XB_mSEND_ACTIVE_WARNS_STS           NULL

#define XB_mSEND_SW_VER_STS                 NULL

#define XB_mSEND_STATE_EVT_LOG_STS          NULL

#define XB_mSEND_HW_REV_STS                 NULL


#endif
