/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup scrftapprxtx scrftapprxtx
  @{

    @brief 
      Macro definitions used by the SmartCraft application
      receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef SCRFTAPPRXTX_H
#define SCRFTAPPRXTX_H

#define SCRFT_mRX_CHECK                     NULL
#define SCRFT_mRX_HANDLER                   NULL

#define SCRFT_mRECV_AC_IN_STS1              NULL
#define SCRFT_mSEND_AC_IN_STS1              NULL

#define SCRFT_mSEND_AC_IN_STS2              NULL

#define SCRFT_mSEND_AC_IN_STS3              NULL

#define SCRFT_mSEND_AC_OUT_STS1             NULL

#define SCRFT_mSEND_AC_OUT_STS2             NULL

#define SCRFT_mSEND_AC_OUT_STS3             NULL

#define SCRFT_mSEND_AGS_STS                 NULL

#define SCRFT_mSEND_BATT_DETAIL_STS         NULL

#define SCRFT_mSEND_BATT_STS                NULL

#define SCRFT_mSEND_CHG_STS                 NULL

#define SCRFT_mSEND_INV_STS                 NULL


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
