/******************************************************************************

  (c) 2003 - 2024 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup rvcapprxtx rvcapprxtx
  @{

    @brief 
      Default macro definitions used by the RV-C application receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef RVCAPPRXTX_H
#define RVCAPPRXTX_H

// Read the application's definitions first
#include "apprxtx.h"

#ifndef RVC_mRX_CHECK
#define RVC_mRX_CHECK                       NULL
#endif

#ifndef RVC_mRX_HANDLER
#define RVC_mRX_HANDLER                     NULL
#endif

#ifndef RVC_mRECV_AC_FLT_CTRL_CFG_CMD1
#define RVC_mRECV_AC_FLT_CTRL_CFG_CMD1      NULL
#endif
#ifndef RVC_mSEND_AC_FLT_CTRL_CFG_CMD1
#define RVC_mSEND_AC_FLT_CTRL_CFG_CMD1      NULL
#endif

#ifndef RVC_mRECV_AC_FLT_CTRL_CFG_CMD2
#define RVC_mRECV_AC_FLT_CTRL_CFG_CMD2      NULL
#endif
#ifndef RVC_mSEND_AC_FLT_CTRL_CFG_CMD2
#define RVC_mSEND_AC_FLT_CTRL_CFG_CMD2      NULL
#endif

#ifndef RVC_mRECV_AC_FLT_CTRL_CFG_STS1
#define RVC_mRECV_AC_FLT_CTRL_CFG_STS1      NULL
#endif
#ifndef RVC_mSEND_AC_FLT_CTRL_CFG_STS1
#define RVC_mSEND_AC_FLT_CTRL_CFG_STS1      NULL
#endif

#ifndef RVC_mRECV_AC_FLT_CTRL_CFG_STS2
#define RVC_mRECV_AC_FLT_CTRL_CFG_STS2      NULL
#endif
#ifndef RVC_mSEND_AC_FLT_CTRL_CFG_STS2
#define RVC_mSEND_AC_FLT_CTRL_CFG_STS2      NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_CMD_AMB_TEMP
#define RVC_mRECV_AGS_CRIT_CMD_AMB_TEMP     NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_CMD_AMB_TEMP
#define RVC_mSEND_AGS_CRIT_CMD_AMB_TEMP     NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_CMD_DC_I
#define RVC_mRECV_AGS_CRIT_CMD_DC_I         NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_CMD_DC_I
#define RVC_mSEND_AGS_CRIT_CMD_DC_I         NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_CMD_DC_SOC
#define RVC_mRECV_AGS_CRIT_CMD_DC_SOC       NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_CMD_DC_SOC
#define RVC_mSEND_AGS_CRIT_CMD_DC_SOC       NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_CMD_DC_V
#define RVC_mRECV_AGS_CRIT_CMD_DC_V         NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_CMD_DC_V
#define RVC_mSEND_AGS_CRIT_CMD_DC_V         NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_CMD_XFER_AC_V
#define RVC_mRECV_AGS_CRIT_CMD_XFER_AC_V    NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_CMD_XFER_AC_V
#define RVC_mSEND_AGS_CRIT_CMD_XFER_AC_V    NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_STS_AMB_TEMP
#define RVC_mRECV_AGS_CRIT_STS_AMB_TEMP     NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_STS_AMB_TEMP
#define RVC_mSEND_AGS_CRIT_STS_AMB_TEMP     NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_STS_DC_I
#define RVC_mRECV_AGS_CRIT_STS_DC_I         NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_STS_DC_I
#define RVC_mSEND_AGS_CRIT_STS_DC_I         NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_STS_DC_SOC
#define RVC_mRECV_AGS_CRIT_STS_DC_SOC       NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_STS_DC_SOC
#define RVC_mSEND_AGS_CRIT_STS_DC_SOC       NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_STS_DC_V
#define RVC_mRECV_AGS_CRIT_STS_DC_V         NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_STS_DC_V
#define RVC_mSEND_AGS_CRIT_STS_DC_V         NULL
#endif

#ifndef RVC_mRECV_AGS_CRIT_STS_XFER_AC_V
#define RVC_mRECV_AGS_CRIT_STS_XFER_AC_V    NULL
#endif
#ifndef RVC_mSEND_AGS_CRIT_STS_XFER_AC_V
#define RVC_mSEND_AGS_CRIT_STS_XFER_AC_V    NULL
#endif

#ifndef RVC_mRECV_ALARM_CMD
#define RVC_mRECV_ALARM_CMD                 NULL
#endif
#ifndef RVC_mSEND_ALARM_CMD
#define RVC_mSEND_ALARM_CMD                 NULL
#endif

#ifndef RVC_mRECV_ALARM_STS
#define RVC_mRECV_ALARM_STS                 NULL
#endif
#ifndef RVC_mSEND_ALARM_STS
#define RVC_mSEND_ALARM_STS                 NULL
#endif

#ifndef RVC_mRECV_BATT_CMD
#define RVC_mRECV_BATT_CMD                  NULL
#endif
#ifndef RVC_mSEND_BATT_CMD
#define RVC_mSEND_BATT_CMD                  NULL
#endif

#ifndef RVC_mRECV_BATT_STS1
#define RVC_mRECV_BATT_STS1                 NULL
#endif

#ifndef RVC_mRECV_BATT_STS11
#define RVC_mRECV_BATT_STS11                NULL
#endif

#ifndef RVC_mRECV_BATT_STS2
#define RVC_mRECV_BATT_STS2                 NULL
#endif

#ifndef RVC_mRECV_BATT_STS3
#define RVC_mRECV_BATT_STS3                 NULL
#endif

#ifndef RVC_mRECV_BATT_STS4
#define RVC_mRECV_BATT_STS4                 NULL
#endif

#ifndef RVC_mRECV_BATT_STS6
#define RVC_mRECV_BATT_STS6                 NULL
#endif

#ifndef RVC_mRECV_BATT_SUMM
#define RVC_mRECV_BATT_SUMM                 NULL
#endif

#ifndef RVC_mRECV_CHG_AC_FLT_CFG_CMD1
#define RVC_mRECV_CHG_AC_FLT_CFG_CMD1       NULL
#endif
#ifndef RVC_mSEND_CHG_AC_FLT_CFG_CMD1
#define RVC_mSEND_CHG_AC_FLT_CFG_CMD1       NULL
#endif

#ifndef RVC_mRECV_CHG_AC_FLT_CFG_CMD2
#define RVC_mRECV_CHG_AC_FLT_CFG_CMD2       NULL
#endif
#ifndef RVC_mSEND_CHG_AC_FLT_CFG_CMD2
#define RVC_mSEND_CHG_AC_FLT_CFG_CMD2       NULL
#endif

#ifndef RVC_mRECV_CHG_AC_FLT_CFG_STS1
#define RVC_mRECV_CHG_AC_FLT_CFG_STS1       NULL
#endif
#ifndef RVC_mSEND_CHG_AC_FLT_CFG_STS1
#define RVC_mSEND_CHG_AC_FLT_CFG_STS1       NULL
#endif

#ifndef RVC_mRECV_CHG_AC_FLT_CFG_STS2
#define RVC_mRECV_CHG_AC_FLT_CFG_STS2       NULL
#endif
#ifndef RVC_mSEND_CHG_AC_FLT_CFG_STS2
#define RVC_mSEND_CHG_AC_FLT_CFG_STS2       NULL
#endif

#ifndef RVC_mRECV_CHG_AC_STS1
#define RVC_mRECV_CHG_AC_STS1               NULL
#endif
#ifndef RVC_mSEND_CHG_AC_STS1
#define RVC_mSEND_CHG_AC_STS1               NULL
#endif

#ifndef RVC_mRECV_CHG_AC_STS2
#define RVC_mRECV_CHG_AC_STS2               NULL
#endif
#ifndef RVC_mSEND_CHG_AC_STS2
#define RVC_mSEND_CHG_AC_STS2               NULL
#endif

#ifndef RVC_mRECV_CHG_AC_STS3
#define RVC_mRECV_CHG_AC_STS3               NULL
#endif
#ifndef RVC_mSEND_CHG_AC_STS3
#define RVC_mSEND_CHG_AC_STS3               NULL
#endif

#ifndef RVC_mRECV_CHG_AC_STS4
#define RVC_mRECV_CHG_AC_STS4               NULL
#endif
#ifndef RVC_mSEND_CHG_AC_STS4
#define RVC_mSEND_CHG_AC_STS4               NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_CMD1
#define RVC_mRECV_CHG_CFG_CMD1              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_CMD1
#define RVC_mSEND_CHG_CFG_CMD1              NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_CMD2
#define RVC_mRECV_CHG_CFG_CMD2              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_CMD2
#define RVC_mSEND_CHG_CFG_CMD2              NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_CMD3
#define RVC_mRECV_CHG_CFG_CMD3              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_CMD3
#define RVC_mSEND_CHG_CFG_CMD3              NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_CMD4
#define RVC_mRECV_CHG_CFG_CMD4              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_CMD4
#define RVC_mSEND_CHG_CFG_CMD4              NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_STS1
#define RVC_mRECV_CHG_CFG_STS1              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_STS1
#define RVC_mSEND_CHG_CFG_STS1              NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_STS2
#define RVC_mRECV_CHG_CFG_STS2              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_STS2
#define RVC_mSEND_CHG_CFG_STS2              NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_STS3
#define RVC_mRECV_CHG_CFG_STS3              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_STS3
#define RVC_mSEND_CHG_CFG_STS3              NULL
#endif

#ifndef RVC_mRECV_CHG_CFG_STS4
#define RVC_mRECV_CHG_CFG_STS4              NULL
#endif
#ifndef RVC_mSEND_CHG_CFG_STS4
#define RVC_mSEND_CHG_CFG_STS4              NULL
#endif

#ifndef RVC_mRECV_CHG_CMD
#define RVC_mRECV_CHG_CMD                   NULL
#endif
#ifndef RVC_mSEND_CHG_CMD
#define RVC_mSEND_CHG_CMD                   NULL
#endif

#ifndef RVC_mRECV_CHG_EQLZ_CFG_CMD
#define RVC_mRECV_CHG_EQLZ_CFG_CMD          NULL
#endif
#ifndef RVC_mSEND_CHG_EQLZ_CFG_CMD
#define RVC_mSEND_CHG_EQLZ_CFG_CMD          NULL
#endif

#ifndef RVC_mRECV_CHG_EQLZ_CFG_STS
#define RVC_mRECV_CHG_EQLZ_CFG_STS          NULL
#endif
#ifndef RVC_mSEND_CHG_EQLZ_CFG_STS
#define RVC_mSEND_CHG_EQLZ_CFG_STS          NULL
#endif

#ifndef RVC_mRECV_CHG_EQLZ_STS
#define RVC_mRECV_CHG_EQLZ_STS              NULL
#endif
#ifndef RVC_mSEND_CHG_EQLZ_STS
#define RVC_mSEND_CHG_EQLZ_STS              NULL
#endif

#ifndef RVC_mRECV_CHG_STATS_STS
#define RVC_mRECV_CHG_STATS_STS             NULL
#endif
#ifndef RVC_mSEND_CHG_STATS_STS
#define RVC_mSEND_CHG_STATS_STS             NULL
#endif

#ifndef RVC_mRECV_CHG_STS
#define RVC_mRECV_CHG_STS                   NULL
#endif
#ifndef RVC_mSEND_CHG_STS
#define RVC_mSEND_CHG_STS                   NULL
#endif

#ifndef RVC_mRECV_CHG_STS2
#define RVC_mRECV_CHG_STS2                  NULL
#endif
#ifndef RVC_mSEND_CHG_STS2
#define RVC_mSEND_CHG_STS2                  NULL
#endif

#ifndef RVC_mRECV_CHG_STS3
#define RVC_mRECV_CHG_STS3                  NULL
#endif
#ifndef RVC_mSEND_CHG_STS3
#define RVC_mSEND_CHG_STS3                  NULL
#endif

#ifndef RVC_mRECV_COMM_STS1
#define RVC_mRECV_COMM_STS1                 NULL
#endif
#ifndef RVC_mSEND_COMM_STS1
#define RVC_mSEND_COMM_STS1                 NULL
#endif

#ifndef RVC_mRECV_COMM_STS2
#define RVC_mRECV_COMM_STS2                 NULL
#endif
#ifndef RVC_mSEND_COMM_STS2
#define RVC_mSEND_COMM_STS2                 NULL
#endif

#ifndef RVC_mRECV_COMM_STS3
#define RVC_mRECV_COMM_STS3                 NULL
#endif
#ifndef RVC_mSEND_COMM_STS3
#define RVC_mSEND_COMM_STS3                 NULL
#endif

#ifndef RVC_mRECV_DC_SRC_CFG_CMD3
#define RVC_mRECV_DC_SRC_CFG_CMD3           NULL
#endif
#ifndef RVC_mSEND_DC_SRC_CFG_CMD3
#define RVC_mSEND_DC_SRC_CFG_CMD3           NULL
#endif

#ifndef RVC_mRECV_DC_SRC_CMD
#define RVC_mRECV_DC_SRC_CMD                NULL
#endif
#ifndef RVC_mSEND_DC_SRC_CMD
#define RVC_mSEND_DC_SRC_CMD                NULL
#endif

#ifndef RVC_mRECV_DC_SRC_CONN_STS
#define RVC_mRECV_DC_SRC_CONN_STS           NULL
#endif
#ifndef RVC_mSEND_DC_SRC_CONN_STS
#define RVC_mSEND_DC_SRC_CONN_STS           NULL
#endif

#ifndef RVC_mRECV_DC_SRC_STS1
#define RVC_mRECV_DC_SRC_STS1               NULL
#endif
#ifndef RVC_mSEND_DC_SRC_STS1
#define RVC_mSEND_DC_SRC_STS1               NULL
#endif

#ifndef RVC_mRECV_DC_SRC_STS11
#define RVC_mRECV_DC_SRC_STS11              NULL
#endif
#ifndef RVC_mSEND_DC_SRC_STS11
#define RVC_mSEND_DC_SRC_STS11              NULL
#endif

#ifndef RVC_mRECV_DC_SRC_STS2
#define RVC_mRECV_DC_SRC_STS2               NULL
#endif
#ifndef RVC_mSEND_DC_SRC_STS2
#define RVC_mSEND_DC_SRC_STS2               NULL
#endif

#ifndef RVC_mRECV_DC_SRC_STS3
#define RVC_mRECV_DC_SRC_STS3               NULL
#endif
#ifndef RVC_mSEND_DC_SRC_STS3
#define RVC_mSEND_DC_SRC_STS3               NULL
#endif

#ifndef RVC_mRECV_DC_SRC_STS4
#define RVC_mRECV_DC_SRC_STS4               NULL
#endif
#ifndef RVC_mSEND_DC_SRC_STS4
#define RVC_mSEND_DC_SRC_STS4               NULL
#endif

#ifndef RVC_mRECV_DC_SRC_STS6
#define RVC_mRECV_DC_SRC_STS6               NULL
#endif
#ifndef RVC_mSEND_DC_SRC_STS6
#define RVC_mSEND_DC_SRC_STS6               NULL
#endif

#ifndef RVC_mRECV_DEVICE_STATE_SYNC
#define RVC_mRECV_DEVICE_STATE_SYNC         NULL
#endif
#ifndef RVC_mSEND_DEVICE_STATE_SYNC
#define RVC_mSEND_DEVICE_STATE_SYNC         NULL
#endif

#ifndef RVC_mSEND_DIAG_MSG1
#define RVC_mSEND_DIAG_MSG1                 NULL
#endif

#ifndef RVC_mSEND_FILE_DNLD_BLK
#define RVC_mSEND_FILE_DNLD_BLK             NULL
#endif

#ifndef RVC_mSEND_FILE_DNLD_INF
#define RVC_mSEND_FILE_DNLD_INF             NULL
#endif

#ifndef RVC_mRECV_FILE_DNLD_STS
#define RVC_mRECV_FILE_DNLD_STS             NULL
#endif

#ifndef RVC_mRECV_GEN_CMD
#define RVC_mRECV_GEN_CMD                   NULL
#endif
#ifndef RVC_mSEND_GEN_CMD
#define RVC_mSEND_GEN_CMD                   NULL
#endif

#ifndef RVC_mRECV_GEN_DEMAND_CMD
#define RVC_mRECV_GEN_DEMAND_CMD            NULL
#endif
#ifndef RVC_mSEND_GEN_DEMAND_CMD
#define RVC_mSEND_GEN_DEMAND_CMD            NULL
#endif

#ifndef RVC_mRECV_GEN_DEMAND_STS
#define RVC_mRECV_GEN_DEMAND_STS            NULL
#endif
#ifndef RVC_mSEND_GEN_DEMAND_STS
#define RVC_mSEND_GEN_DEMAND_STS            NULL
#endif

#ifndef RVC_mRECV_GEN_RST
#define RVC_mRECV_GEN_RST                   NULL
#endif
#ifndef RVC_mSEND_GEN_RST
#define RVC_mSEND_GEN_RST                   NULL
#endif

#ifndef RVC_mRECV_GEN_START_CFG_CMD
#define RVC_mRECV_GEN_START_CFG_CMD         NULL
#endif
#ifndef RVC_mSEND_GEN_START_CFG_CMD
#define RVC_mSEND_GEN_START_CFG_CMD         NULL
#endif

#ifndef RVC_mRECV_GEN_START_CFG_STS
#define RVC_mRECV_GEN_START_CFG_STS         NULL
#endif
#ifndef RVC_mSEND_GEN_START_CFG_STS
#define RVC_mSEND_GEN_START_CFG_STS         NULL
#endif

#ifndef RVC_mRECV_GEN_STS1
#define RVC_mRECV_GEN_STS1                  NULL
#endif
#ifndef RVC_mSEND_GEN_STS1
#define RVC_mSEND_GEN_STS1                  NULL
#endif

#ifndef RVC_mRECV_GEN_STS2
#define RVC_mRECV_GEN_STS2                  NULL
#endif
#ifndef RVC_mSEND_GEN_STS2
#define RVC_mSEND_GEN_STS2                  NULL
#endif

#ifndef RVC_mRECV_INST_ASSIGN
#define RVC_mRECV_INST_ASSIGN               NULL
#endif
#ifndef RVC_mSEND_INST_ASSIGN
#define RVC_mSEND_INST_ASSIGN               NULL
#endif

#ifndef RVC_mRECV_INST_STS
#define RVC_mRECV_INST_STS                  NULL
#endif
#ifndef RVC_mSEND_INST_STS
#define RVC_mSEND_INST_STS                  NULL
#endif

#ifndef RVC_mRECV_INV_AC_FLT_CFG_CMD1
#define RVC_mRECV_INV_AC_FLT_CFG_CMD1       NULL
#endif
#ifndef RVC_mSEND_INV_AC_FLT_CFG_CMD1
#define RVC_mSEND_INV_AC_FLT_CFG_CMD1       NULL
#endif

#ifndef RVC_mRECV_INV_AC_FLT_CFG_STS1
#define RVC_mRECV_INV_AC_FLT_CFG_STS1       NULL
#endif
#ifndef RVC_mSEND_INV_AC_FLT_CFG_STS1
#define RVC_mSEND_INV_AC_FLT_CFG_STS1       NULL
#endif

#ifndef RVC_mRECV_INV_AC_STS1
#define RVC_mRECV_INV_AC_STS1               NULL
#endif
#ifndef RVC_mSEND_INV_AC_STS1
#define RVC_mSEND_INV_AC_STS1               NULL
#endif

#ifndef RVC_mRECV_INV_AC_STS2
#define RVC_mRECV_INV_AC_STS2               NULL
#endif
#ifndef RVC_mSEND_INV_AC_STS2
#define RVC_mSEND_INV_AC_STS2               NULL
#endif

#ifndef RVC_mRECV_INV_AC_STS3
#define RVC_mRECV_INV_AC_STS3               NULL
#endif
#ifndef RVC_mSEND_INV_AC_STS3
#define RVC_mSEND_INV_AC_STS3               NULL
#endif

#ifndef RVC_mRECV_INV_AC_STS4
#define RVC_mRECV_INV_AC_STS4               NULL
#endif
#ifndef RVC_mSEND_INV_AC_STS4
#define RVC_mSEND_INV_AC_STS4               NULL
#endif

#ifndef RVC_mRECV_INV_APS_STS
#define RVC_mRECV_INV_APS_STS               NULL
#endif
#ifndef RVC_mSEND_INV_APS_STS
#define RVC_mSEND_INV_APS_STS               NULL
#endif

#ifndef RVC_mRECV_INV_CFG_CMD1
#define RVC_mRECV_INV_CFG_CMD1              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_CMD1
#define RVC_mSEND_INV_CFG_CMD1              NULL
#endif

#ifndef RVC_mRECV_INV_CFG_CMD2
#define RVC_mRECV_INV_CFG_CMD2              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_CMD2
#define RVC_mSEND_INV_CFG_CMD2              NULL
#endif

#ifndef RVC_mRECV_INV_CFG_CMD3
#define RVC_mRECV_INV_CFG_CMD3              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_CMD3
#define RVC_mSEND_INV_CFG_CMD3              NULL
#endif

#ifndef RVC_mRECV_INV_CFG_CMD4
#define RVC_mRECV_INV_CFG_CMD4              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_CMD4
#define RVC_mSEND_INV_CFG_CMD4              NULL
#endif

#ifndef RVC_mRECV_INV_CFG_STS1
#define RVC_mRECV_INV_CFG_STS1              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_STS1
#define RVC_mSEND_INV_CFG_STS1              NULL
#endif

#ifndef RVC_mRECV_INV_CFG_STS2
#define RVC_mRECV_INV_CFG_STS2              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_STS2
#define RVC_mSEND_INV_CFG_STS2              NULL
#endif

#ifndef RVC_mRECV_INV_CFG_STS3
#define RVC_mRECV_INV_CFG_STS3              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_STS3
#define RVC_mSEND_INV_CFG_STS3              NULL
#endif

#ifndef RVC_mRECV_INV_CFG_STS4
#define RVC_mRECV_INV_CFG_STS4              NULL
#endif
#ifndef RVC_mSEND_INV_CFG_STS4
#define RVC_mSEND_INV_CFG_STS4              NULL
#endif

#ifndef RVC_mRECV_INV_CMD
#define RVC_mRECV_INV_CMD                   NULL
#endif
#ifndef RVC_mSEND_INV_CMD
#define RVC_mSEND_INV_CMD                   NULL
#endif

#ifndef RVC_mRECV_INV_DC_STS
#define RVC_mRECV_INV_DC_STS                NULL
#endif
#ifndef RVC_mSEND_INV_DC_STS
#define RVC_mSEND_INV_DC_STS                NULL
#endif

#ifndef RVC_mRECV_INV_HV_DC_BUS_STS
#define RVC_mRECV_INV_HV_DC_BUS_STS         NULL
#endif
#ifndef RVC_mSEND_INV_HV_DC_BUS_STS
#define RVC_mSEND_INV_HV_DC_BUS_STS         NULL
#endif

#ifndef RVC_mRECV_INV_OPS_STS
#define RVC_mRECV_INV_OPS_STS               NULL
#endif
#ifndef RVC_mSEND_INV_OPS_STS
#define RVC_mSEND_INV_OPS_STS               NULL
#endif

#ifndef RVC_mRECV_INV_STATS_STS
#define RVC_mRECV_INV_STATS_STS             NULL
#endif
#ifndef RVC_mSEND_INV_STATS_STS
#define RVC_mSEND_INV_STATS_STS             NULL
#endif

#ifndef RVC_mRECV_INV_STS
#define RVC_mRECV_INV_STS                   NULL
#endif
#ifndef RVC_mSEND_INV_STS
#define RVC_mSEND_INV_STS                   NULL
#endif

#ifndef RVC_mRECV_INV_TEMP_STS
#define RVC_mRECV_INV_TEMP_STS              NULL
#endif
#ifndef RVC_mSEND_INV_TEMP_STS
#define RVC_mSEND_INV_TEMP_STS              NULL
#endif

#ifndef RVC_mRECV_INV_TEMP_STS2
#define RVC_mRECV_INV_TEMP_STS2             NULL
#endif
#ifndef RVC_mSEND_INV_TEMP_STS2
#define RVC_mSEND_INV_TEMP_STS2             NULL
#endif

#ifndef RVC_mRECV_ISO_ACK
#define RVC_mRECV_ISO_ACK                   NULL
#endif
#ifndef RVC_mSEND_ISO_ACK
#define RVC_mSEND_ISO_ACK                   NULL
#endif

#ifndef RVC_mRECV_PM_AC_STS_RMS
#define RVC_mRECV_PM_AC_STS_RMS             NULL
#endif
#ifndef RVC_mSEND_PM_AC_STS_RMS
#define RVC_mSEND_PM_AC_STS_RMS             NULL
#endif

#ifndef RVC_mRECV_PM_AC_XFER_SW_STS
#define RVC_mRECV_PM_AC_XFER_SW_STS         NULL
#endif
#ifndef RVC_mSEND_PM_AC_XFER_SW_STS
#define RVC_mSEND_PM_AC_XFER_SW_STS         NULL
#endif

#ifndef RVC_mRECV_PM_ASSOC_CFG
#define RVC_mRECV_PM_ASSOC_CFG              NULL
#endif
#ifndef RVC_mSEND_PM_ASSOC_CFG
#define RVC_mSEND_PM_ASSOC_CFG              NULL
#endif

#ifndef RVC_mRECV_PM_ASSOC_STS
#define RVC_mRECV_PM_ASSOC_STS              NULL
#endif
#ifndef RVC_mSEND_PM_ASSOC_STS
#define RVC_mSEND_PM_ASSOC_STS              NULL
#endif

#ifndef RVC_mRECV_PM_CHG_STS
#define RVC_mRECV_PM_CHG_STS                NULL
#endif
#ifndef RVC_mSEND_PM_CHG_STS
#define RVC_mSEND_PM_CHG_STS                NULL
#endif

#ifndef RVC_mRECV_PM_DEV_MD_CFG
#define RVC_mRECV_PM_DEV_MD_CFG             NULL
#endif
#ifndef RVC_mSEND_PM_DEV_MD_CFG
#define RVC_mSEND_PM_DEV_MD_CFG             NULL
#endif

#ifndef RVC_mRECV_PM_DEV_MD_STS
#define RVC_mRECV_PM_DEV_MD_STS             NULL
#endif
#ifndef RVC_mSEND_PM_DEV_MD_STS
#define RVC_mSEND_PM_DEV_MD_STS             NULL
#endif

#ifndef RVC_mRECV_PM_FXCC_CFG_CMD
#define RVC_mRECV_PM_FXCC_CFG_CMD           NULL
#endif
#ifndef RVC_mSEND_PM_FXCC_CFG_CMD
#define RVC_mSEND_PM_FXCC_CFG_CMD           NULL
#endif

#ifndef RVC_mRECV_PM_FXCC_CFG_STS
#define RVC_mRECV_PM_FXCC_CFG_STS           NULL
#endif
#ifndef RVC_mSEND_PM_FXCC_CFG_STS
#define RVC_mSEND_PM_FXCC_CFG_STS           NULL
#endif

#ifndef RVC_mRECV_PM_GET_CONFIG_PARAM
#define RVC_mRECV_PM_GET_CONFIG_PARAM       NULL
#endif
#ifndef RVC_mSEND_PM_GET_CONFIG_PARAM
#define RVC_mSEND_PM_GET_CONFIG_PARAM       NULL
#endif

#ifndef RVC_mRECV_PM_GET_STATUS_PARAM
#define RVC_mRECV_PM_GET_STATUS_PARAM       NULL
#endif
#ifndef RVC_mSEND_PM_GET_STATUS_PARAM
#define RVC_mSEND_PM_GET_STATUS_PARAM       NULL
#endif

#ifndef RVC_mRECV_PM_INV_CTRL_CMD
#define RVC_mRECV_PM_INV_CTRL_CMD           NULL
#endif
#ifndef RVC_mSEND_PM_INV_CTRL_CMD
#define RVC_mSEND_PM_INV_CTRL_CMD           NULL
#endif

#ifndef RVC_mRECV_PM_INV_LD_SH_STS
#define RVC_mRECV_PM_INV_LD_SH_STS          NULL
#endif
#ifndef RVC_mSEND_PM_INV_LD_SH_STS
#define RVC_mSEND_PM_INV_LD_SH_STS          NULL
#endif

#ifndef RVC_mRECV_PM_INV_STS
#define RVC_mRECV_PM_INV_STS                NULL
#endif
#ifndef RVC_mSEND_PM_INV_STS
#define RVC_mSEND_PM_INV_STS                NULL
#endif

#ifndef RVC_mRECV_PM_LITHIONICS_CMD
#define RVC_mRECV_PM_LITHIONICS_CMD         NULL
#endif
#ifndef RVC_mSEND_PM_LITHIONICS_CMD
#define RVC_mSEND_PM_LITHIONICS_CMD         NULL
#endif

#ifndef RVC_mRECV_PM_LITHIONICS_STS
#define RVC_mRECV_PM_LITHIONICS_STS         NULL
#endif
#ifndef RVC_mSEND_PM_LITHIONICS_STS
#define RVC_mSEND_PM_LITHIONICS_STS         NULL
#endif

#ifndef RVC_mRECV_PM_PARAM_ASSOC_CFG
#define RVC_mRECV_PM_PARAM_ASSOC_CFG        NULL
#endif
#ifndef RVC_mSEND_PM_PARAM_ASSOC_CFG
#define RVC_mSEND_PM_PARAM_ASSOC_CFG        NULL
#endif

#ifndef RVC_mRECV_PM_PARAM_AUX_CFG
#define RVC_mRECV_PM_PARAM_AUX_CFG          NULL
#endif
#ifndef RVC_mSEND_PM_PARAM_AUX_CFG
#define RVC_mSEND_PM_PARAM_AUX_CFG          NULL
#endif

#ifndef RVC_mRECV_PM_PARAM_AUX_CFG_TRIG_DLY
#define RVC_mRECV_PM_PARAM_AUX_CFG_TRIG_DLY    NULL
#endif
#ifndef RVC_mSEND_PM_PARAM_AUX_CFG_TRIG_DLY
#define RVC_mSEND_PM_PARAM_AUX_CFG_TRIG_DLY    NULL
#endif

#ifndef RVC_mRECV_PM_PARAM_AUX_CFG_TRIG_LVL
#define RVC_mRECV_PM_PARAM_AUX_CFG_TRIG_LVL    NULL
#endif
#ifndef RVC_mSEND_PM_PARAM_AUX_CFG_TRIG_LVL
#define RVC_mSEND_PM_PARAM_AUX_CFG_TRIG_LVL    NULL
#endif

#ifndef RVC_mRECV_PM_PARAM_AUX_STS
#define RVC_mRECV_PM_PARAM_AUX_STS          NULL
#endif
#ifndef RVC_mSEND_PM_PARAM_AUX_STS
#define RVC_mSEND_PM_PARAM_AUX_STS          NULL
#endif

#ifndef RVC_mRECV_PM_PARAM_DEV_MD_CFG
#define RVC_mRECV_PM_PARAM_DEV_MD_CFG       NULL
#endif
#ifndef RVC_mSEND_PM_PARAM_DEV_MD_CFG
#define RVC_mSEND_PM_PARAM_DEV_MD_CFG       NULL
#endif

#ifndef RVC_mRECV_PM_PPN_NAK_RSP
#define RVC_mRECV_PM_PPN_NAK_RSP            NULL
#endif
#ifndef RVC_mSEND_PM_PPN_NAK_RSP
#define RVC_mSEND_PM_PPN_NAK_RSP            NULL
#endif

#ifndef RVC_mRECV_PM_PPN_READ_CMD
#define RVC_mRECV_PM_PPN_READ_CMD           NULL
#endif
#ifndef RVC_mSEND_PM_PPN_READ_CMD
#define RVC_mSEND_PM_PPN_READ_CMD           NULL
#endif

#ifndef RVC_mRECV_PM_PPN_READ_RSP
#define RVC_mRECV_PM_PPN_READ_RSP           NULL
#endif
#ifndef RVC_mSEND_PM_PPN_READ_RSP
#define RVC_mSEND_PM_PPN_READ_RSP           NULL
#endif

#ifndef RVC_mRECV_PM_PPN_SESSION_CMD
#define RVC_mRECV_PM_PPN_SESSION_CMD        NULL
#endif
#ifndef RVC_mSEND_PM_PPN_SESSION_CMD
#define RVC_mSEND_PM_PPN_SESSION_CMD        NULL
#endif

#ifndef RVC_mRECV_PM_PPN_SESSION_RSP
#define RVC_mRECV_PM_PPN_SESSION_RSP        NULL
#endif
#ifndef RVC_mSEND_PM_PPN_SESSION_RSP
#define RVC_mSEND_PM_PPN_SESSION_RSP        NULL
#endif

#ifndef RVC_mRECV_PM_PPN_WRITE_CMD
#define RVC_mRECV_PM_PPN_WRITE_CMD          NULL
#endif
#ifndef RVC_mSEND_PM_PPN_WRITE_CMD
#define RVC_mSEND_PM_PPN_WRITE_CMD          NULL
#endif

#ifndef RVC_mRECV_PM_PPN_WRITE_RSP
#define RVC_mRECV_PM_PPN_WRITE_RSP          NULL
#endif
#ifndef RVC_mSEND_PM_PPN_WRITE_RSP
#define RVC_mSEND_PM_PPN_WRITE_RSP          NULL
#endif

#ifndef RVC_mRECV_PM_REQ
#define RVC_mRECV_PM_REQ                    NULL
#endif
#ifndef RVC_mSEND_PM_REQ
#define RVC_mSEND_PM_REQ                    NULL
#endif

#ifndef RVC_mRECV_PM_RPC_CMD
#define RVC_mRECV_PM_RPC_CMD                NULL
#endif
#ifndef RVC_mSEND_PM_RPC_CMD
#define RVC_mSEND_PM_RPC_CMD                NULL
#endif

#ifndef RVC_mRECV_PM_SET_CONFIG_PARAM
#define RVC_mRECV_PM_SET_CONFIG_PARAM       NULL
#endif
#ifndef RVC_mSEND_PM_SET_CONFIG_PARAM
#define RVC_mSEND_PM_SET_CONFIG_PARAM       NULL
#endif

#ifndef RVC_mRECV_PM_SW_VER_STS
#define RVC_mRECV_PM_SW_VER_STS             NULL
#endif
#ifndef RVC_mSEND_PM_SW_VER_STS
#define RVC_mSEND_PM_SW_VER_STS             NULL
#endif

#ifndef RVC_mRECV_PROD_IDENT
#define RVC_mRECV_PROD_IDENT                NULL
#endif
#ifndef RVC_mSEND_PROD_IDENT
#define RVC_mSEND_PROD_IDENT                NULL
#endif

#ifndef RVC_mRECV_PROD_INFO_STS
#define RVC_mRECV_PROD_INFO_STS             NULL
#endif

#ifndef RVC_mRECV_SCC_ARRAY_STS
#define RVC_mRECV_SCC_ARRAY_STS             NULL
#endif

#ifndef RVC_mRECV_SCC_BATT_STS
#define RVC_mRECV_SCC_BATT_STS              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_CMD
#define RVC_mRECV_SCC_CFG_CMD               NULL
#endif
#ifndef RVC_mSEND_SCC_CFG_CMD
#define RVC_mSEND_SCC_CFG_CMD               NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_CMD2
#define RVC_mRECV_SCC_CFG_CMD2              NULL
#endif
#ifndef RVC_mSEND_SCC_CFG_CMD2
#define RVC_mSEND_SCC_CFG_CMD2              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_CMD3
#define RVC_mRECV_SCC_CFG_CMD3              NULL
#endif
#ifndef RVC_mSEND_SCC_CFG_CMD3
#define RVC_mSEND_SCC_CFG_CMD3              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_CMD4
#define RVC_mRECV_SCC_CFG_CMD4              NULL
#endif
#ifndef RVC_mSEND_SCC_CFG_CMD4
#define RVC_mSEND_SCC_CFG_CMD4              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_CMD5
#define RVC_mRECV_SCC_CFG_CMD5              NULL
#endif
#ifndef RVC_mSEND_SCC_CFG_CMD5
#define RVC_mSEND_SCC_CFG_CMD5              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_STS
#define RVC_mRECV_SCC_CFG_STS               NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_STS2
#define RVC_mRECV_SCC_CFG_STS2              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_STS3
#define RVC_mRECV_SCC_CFG_STS3              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_STS4
#define RVC_mRECV_SCC_CFG_STS4              NULL
#endif

#ifndef RVC_mRECV_SCC_CFG_STS5
#define RVC_mRECV_SCC_CFG_STS5              NULL
#endif

#ifndef RVC_mRECV_SCC_CMD
#define RVC_mRECV_SCC_CMD                   NULL
#endif
#ifndef RVC_mSEND_SCC_CMD
#define RVC_mSEND_SCC_CMD                   NULL
#endif

#ifndef RVC_mRECV_SCC_EQLZ_CFG_CMD
#define RVC_mRECV_SCC_EQLZ_CFG_CMD          NULL
#endif
#ifndef RVC_mSEND_SCC_EQLZ_CFG_CMD
#define RVC_mSEND_SCC_EQLZ_CFG_CMD          NULL
#endif

#ifndef RVC_mRECV_SCC_EQLZ_CFG_STS
#define RVC_mRECV_SCC_EQLZ_CFG_STS          NULL
#endif

#ifndef RVC_mRECV_SCC_EQLZ_STS
#define RVC_mRECV_SCC_EQLZ_STS              NULL
#endif

#ifndef RVC_mRECV_SCC_STS
#define RVC_mRECV_SCC_STS                   NULL
#endif

#ifndef RVC_mRECV_SCC_STS2
#define RVC_mRECV_SCC_STS2                  NULL
#endif

#ifndef RVC_mRECV_SCC_STS3
#define RVC_mRECV_SCC_STS3                  NULL
#endif

#ifndef RVC_mRECV_SCC_STS4
#define RVC_mRECV_SCC_STS4                  NULL
#endif

#ifndef RVC_mRECV_SCC_STS5
#define RVC_mRECV_SCC_STS5                  NULL
#endif

#ifndef RVC_mRECV_SCC_STS6
#define RVC_mRECV_SCC_STS6                  NULL
#endif

#ifndef RVC_mRECV_SET_SYS_DATE_TIME
#define RVC_mRECV_SET_SYS_DATE_TIME         NULL
#endif
#ifndef RVC_mSEND_SET_SYS_DATE_TIME
#define RVC_mSEND_SET_SYS_DATE_TIME         NULL
#endif

#ifndef RVC_mRECV_SIMPLE_CALIB_CFG
#define RVC_mRECV_SIMPLE_CALIB_CFG          NULL
#endif
#ifndef RVC_mSEND_SIMPLE_CALIB_CFG
#define RVC_mSEND_SIMPLE_CALIB_CFG          NULL
#endif

#ifndef RVC_mRECV_SW_VER_STS
#define RVC_mRECV_SW_VER_STS                NULL
#endif

#ifndef RVC_mRECV_SYS_DATE_TIME_STS
#define RVC_mRECV_SYS_DATE_TIME_STS         NULL
#endif
#ifndef RVC_mSEND_SYS_DATE_TIME_STS
#define RVC_mSEND_SYS_DATE_TIME_STS         NULL
#endif

#ifndef RVC_mRECV_VIRTUAL_TERMINAL
#define RVC_mRECV_VIRTUAL_TERMINAL          NULL
#endif
#ifndef RVC_mSEND_VIRTUAL_TERMINAL
#define RVC_mSEND_VIRTUAL_TERMINAL          NULL
#endif

#ifndef RVC_mRECV_XB_RESET_CMD
#define RVC_mRECV_XB_RESET_CMD              NULL
#endif


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
