/******************************************************************************

  (c) 2003 - 2024 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup rvcrxtx rvcrxtx
  @{

    @brief 
      Macro definitions used by the RV-C library receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef RVCRXTX_H
#define RVCRXTX_H

// PG Functions include file
#include "xbpgfns.h"

#define RVC_mRECV_ISO_ADDR_CLAIM            NULL
#define RVC_mSEND_ISO_ADDR_CLAIM            NULL

#define RVC_mRECV_ISO_CMD_ADDR              NULL

#define RVC_mRECV_ISO_REQ                   NULL
#define RVC_mSEND_ISO_REQ                   NULL

#define RVC_mRECV_ISO_TP_CONN_MAN_ABORT     NULL
#define RVC_mSEND_ISO_TP_CONN_MAN_ABORT     NULL

#define RVC_mRECV_ISO_TP_CONN_MAN_BAM       NULL
#define RVC_mSEND_ISO_TP_CONN_MAN_BAM       NULL

#define RVC_mRECV_ISO_TP_CONN_MAN_CTS       NULL
#define RVC_mSEND_ISO_TP_CONN_MAN_CTS       NULL

#define RVC_mRECV_ISO_TP_CONN_MAN_EOM       NULL
#define RVC_mSEND_ISO_TP_CONN_MAN_EOM       NULL

#define RVC_mRECV_ISO_TP_CONN_MAN_RTS       NULL
#define RVC_mSEND_ISO_TP_CONN_MAN_RTS       NULL

#define RVC_mRECV_ISO_TP_XFER               NULL
#define RVC_mSEND_ISO_TP_XFER               NULL


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
