/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup n2kapprxtx n2kapprxtx
  @{

    @brief 
      Macro definitions used by the NMEA 2000 application
      receive and send PGN handlers.


  @note
    - Autogenerated.
      While this file is autogenerated... it can not be used as such.
      Rather the contents of this file must be merged with the file used
      by your project.


*******************************************************************************/

#ifndef N2KAPPRXTX_H
#define N2KAPPRXTX_H

#define N2K_mRX_CHECK                       NULL
#define N2K_mRX_HANDLER                     NULL

#define N2K_mSEND_AC_IN_STS                 NULL

#define N2K_mSEND_AC_OUT_STS                NULL

#define N2K_mSEND_AGS_STS                   NULL

#define N2K_mSEND_BATT_DETAIL_STS           NULL

#define N2K_mSEND_BATT_STS                  NULL

#define N2K_mSEND_CHG_STS                   NULL

#define N2K_mSEND_INV_STS                   NULL

#define N2K_mRECV_ISO_ACK                   NULL
#define N2K_mSEND_ISO_ACK                   NULL

#define N2K_mRECV_PROD_INF                  NULL
#define N2K_mSEND_PROD_INF                  NULL

#define N2K_mRECV_SYS_TIME                  NULL
#define N2K_mSEND_SYS_TIME                  NULL

#define N2K_mRECV_TIME_DATE                 NULL
#define N2K_mSEND_TIME_DATE                 NULL


#endif

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
