/******************************************************************************

  (c) 2003 - 2018 Xantrex Canada ULC. All rights reserved.
  All trademarks are owned or licensed by Xantrex Canada ULC,
  its subsidiaries or affiliated companies.

****************************************************************************//**

  @addtogroup n2kpgntbl n2kpgntbl
  @{

    @brief 
      Data structures and lookup table used to convert CAN message buffers
      to and from the structures used by the application level code.


  @note
    - Autogenerated.

*******************************************************************************/

#include "config.h"

#include "n2kudefs.h"
#include "n2krxtx.h"
#include "n2kapprxtx.h"


#ifndef WIN32
#pragma CONST_SEG PGN_DESC
#endif

// Describe the fields of each PGN

// AC Input Status
static const PGN_tzFIELD_DESC XT_FAR azAcInStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_AC_IN_STS *)NULL )->ucAcSrcNum ) ), sizeof( ((N2K_tzPGN_AC_IN_STS *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_SINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_AC_IN_STS *)NULL )->uiExtraCount ) ), sizeof( ((N2K_tzPGN_AC_IN_STS *)NULL )->uiExtraCount ) },
    { PGN_eTYPE_POINTER,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_AC_IN_STS *)NULL )->ptzExtra ) ), sizeof( ((N2K_tzPGN_AC_IN_STS *)NULL )->ptzExtra ) }
};

static const PGN_tzFIELD_DESC XT_FAR azAcInStsExtraFields[] =
{
    { PGN_eTYPE_BIT,   0,   2, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->teLine ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->teLine ) },
    { PGN_eTYPE_BIT,   2,   2, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->teAcceptability ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->teAcceptability ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiVoltage ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiVoltage ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiCurrent ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiCurrent ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiFreq ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiFreq ) },
    { PGN_eTYPE_UINT,  56,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiBreakerSz ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->uiBreakerSz ) },
    { PGN_eTYPE_ULONG,  72,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->ulRealPwr ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->ulRealPwr ) },
    { PGN_eTYPE_ULONG, 104,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->ulReactivePwr ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->ulReactivePwr ) },
    { PGN_eTYPE_SCHAR, 136,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->scPwrFac ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_IN_STS *)NULL )->scPwrFac ) }
};

// AC Output Status
static const PGN_tzFIELD_DESC XT_FAR azAcOutStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_AC_OUT_STS *)NULL )->ucAcSrcNum ) ), sizeof( ((N2K_tzPGN_AC_OUT_STS *)NULL )->ucAcSrcNum ) },
    { PGN_eTYPE_SINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_AC_OUT_STS *)NULL )->uiExtraCount ) ), sizeof( ((N2K_tzPGN_AC_OUT_STS *)NULL )->uiExtraCount ) },
    { PGN_eTYPE_POINTER,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_AC_OUT_STS *)NULL )->ptzExtra ) ), sizeof( ((N2K_tzPGN_AC_OUT_STS *)NULL )->ptzExtra ) }
};

static const PGN_tzFIELD_DESC XT_FAR azAcOutStsExtraFields[] =
{
    { PGN_eTYPE_BIT,   0,   2, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->teLine ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->teLine ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiVoltage ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiVoltage ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiCurrent ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiCurrent ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiFreq ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiFreq ) },
    { PGN_eTYPE_UINT,  56,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiBreakerSz ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->uiBreakerSz ) },
    { PGN_eTYPE_ULONG,  72,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->ulRealPwr ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->ulRealPwr ) },
    { PGN_eTYPE_ULONG, 104,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->ulReactivePwr ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->ulReactivePwr ) },
    { PGN_eTYPE_SCHAR, 136,   1, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->scPwrFac ) ), sizeof( ((N2K_tzPGN_EXTRA_AC_OUT_STS *)NULL )->scPwrFac ) }
};

// AGS Status
static const PGN_tzFIELD_DESC XT_FAR azAgsStsFields[] =
{
    { PGN_eTYPE_BIT,   0,   4, (uint16)( (uint32)&( ((N2K_tzPGN_AGS_STS *)NULL )->ucAgsOpState ) ), sizeof( ((N2K_tzPGN_AGS_STS *)NULL )->ucAgsOpState ) },
    { PGN_eTYPE_BIT,   4,   4, (uint16)( (uint32)&( ((N2K_tzPGN_AGS_STS *)NULL )->ucGenState ) ), sizeof( ((N2K_tzPGN_AGS_STS *)NULL )->ucGenState ) },
    { PGN_eTYPE_BIT,   8,   4, (uint16)( (uint32)&( ((N2K_tzPGN_AGS_STS *)NULL )->ucGenOnReason ) ), sizeof( ((N2K_tzPGN_AGS_STS *)NULL )->ucGenOnReason ) },
    { PGN_eTYPE_BIT,  12,   5, (uint16)( (uint32)&( ((N2K_tzPGN_AGS_STS *)NULL )->ucGenOffReason ) ), sizeof( ((N2K_tzPGN_AGS_STS *)NULL )->ucGenOffReason ) },
    { PGN_eTYPE_BIT,  17,   2, (uint16)( (uint32)&( ((N2K_tzPGN_AGS_STS *)NULL )->teAgsToGenSig ) ), sizeof( ((N2K_tzPGN_AGS_STS *)NULL )->teAgsToGenSig ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_AGS_STS *)NULL )->uiTimeIntvl ) ), sizeof( ((N2K_tzPGN_AGS_STS *)NULL )->uiTimeIntvl ) },
};

// Battery Detailed Status
static const PGN_tzFIELD_DESC XT_FAR azBattDetailStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucSid ) ), sizeof( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucSid ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucBattInst ) ), sizeof( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucBattInst ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoc ) ), sizeof( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoc ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoh ) ), sizeof( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->ucSoh ) },
    { PGN_eTYPE_UINT,  32,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->uiTimeRemain ) ), sizeof( ((N2K_tzPGN_BATT_DETAIL_STS *)NULL )->uiTimeRemain ) },
};

// Battery Status
static const PGN_tzFIELD_DESC XT_FAR azBattStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_STS *)NULL )->ucBattInst ) ), sizeof( ((N2K_tzPGN_BATT_STS *)NULL )->ucBattInst ) },
    { PGN_eTYPE_SINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_STS *)NULL )->siBattPot ) ), sizeof( ((N2K_tzPGN_BATT_STS *)NULL )->siBattPot ) },
    { PGN_eTYPE_SINT,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_STS *)NULL )->siBattCurr ) ), sizeof( ((N2K_tzPGN_BATT_STS *)NULL )->siBattCurr ) },
    { PGN_eTYPE_UINT,  40,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_STS *)NULL )->uiBattCaseTemp ) ), sizeof( ((N2K_tzPGN_BATT_STS *)NULL )->uiBattCaseTemp ) },
    { PGN_eTYPE_UCHAR,  56,   1, (uint16)( (uint32)&( ((N2K_tzPGN_BATT_STS *)NULL )->ucSid ) ), sizeof( ((N2K_tzPGN_BATT_STS *)NULL )->ucSid ) }
};

// Charger Status
static const PGN_tzFIELD_DESC XT_FAR azChgStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_CHG_STS *)NULL )->ucDCSrcNum ) ), sizeof( ((N2K_tzPGN_CHG_STS *)NULL )->ucDCSrcNum ) },
    { PGN_eTYPE_BIT,   8,   5, (uint16)( (uint32)&( ((N2K_tzPGN_CHG_STS *)NULL )->teOpState ) ), sizeof( ((N2K_tzPGN_CHG_STS *)NULL )->teOpState ) },
    { PGN_eTYPE_BIT,  13,   2, (uint16)( (uint32)&( ((N2K_tzPGN_CHG_STS *)NULL )->teChgMode ) ), sizeof( ((N2K_tzPGN_CHG_STS *)NULL )->teChgMode ) },
    { PGN_eTYPE_BIT,  15,   2, (uint16)( (uint32)&( ((N2K_tzPGN_CHG_STS *)NULL )->teChgEnDis ) ), sizeof( ((N2K_tzPGN_CHG_STS *)NULL )->teChgEnDis ) },
    { PGN_eTYPE_BIT,  17,   2, (uint16)( (uint32)&( ((N2K_tzPGN_CHG_STS *)NULL )->teBattTempSensPres ) ), sizeof( ((N2K_tzPGN_CHG_STS *)NULL )->teBattTempSensPres ) },
    { PGN_eTYPE_BIT,  19,   2, (uint16)( (uint32)&( ((N2K_tzPGN_CHG_STS *)NULL )->teEqlzPending ) ), sizeof( ((N2K_tzPGN_CHG_STS *)NULL )->teEqlzPending ) },
    { PGN_eTYPE_UINT,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_CHG_STS *)NULL )->uiEqlzTimeRemain ) ), sizeof( ((N2K_tzPGN_CHG_STS *)NULL )->uiEqlzTimeRemain ) },
};

// Inverter Status
static const PGN_tzFIELD_DESC XT_FAR azInvStsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_INV_STS *)NULL )->ucACSrcNum ) ), sizeof( ((N2K_tzPGN_INV_STS *)NULL )->ucACSrcNum ) },
    { PGN_eTYPE_BIT,   8,   4, (uint16)( (uint32)&( ((N2K_tzPGN_INV_STS *)NULL )->teOpState ) ), sizeof( ((N2K_tzPGN_INV_STS *)NULL )->teOpState ) },
    { PGN_eTYPE_BIT,  12,   2, (uint16)( (uint32)&( ((N2K_tzPGN_INV_STS *)NULL )->teInvEnDis ) ), sizeof( ((N2K_tzPGN_INV_STS *)NULL )->teInvEnDis ) },
    { PGN_eTYPE_BIT,  14,   2, (uint16)( (uint32)&( ((N2K_tzPGN_INV_STS *)NULL )->teBattTempSensPres ) ), sizeof( ((N2K_tzPGN_INV_STS *)NULL )->teBattTempSensPres ) },
};

// ISO Acknowledgment
static const PGN_tzFIELD_DESC XT_FAR azIsoAckFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ACK *)NULL )->teCtrlByte ) ), sizeof( ((N2K_tzPGN_ISO_ACK *)NULL )->teCtrlByte ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ACK *)NULL )->teGroupFunctionValue ) ), sizeof( ((N2K_tzPGN_ISO_ACK *)NULL )->teGroupFunctionValue ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ACK *)NULL )->ulParmGrpNum ) ), sizeof( ((N2K_tzPGN_ISO_ACK *)NULL )->ulParmGrpNum ) }
};

// ISO Address Claim
static const PGN_tzFIELD_DESC XT_FAR azIsoAddrClaimFields[] =
{
    { PGN_eTYPE_BIT,   0,  21, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ulUniqueNumber ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ulUniqueNumber ) },
    { PGN_eTYPE_BIT,  21,  11, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->uiManufacturerCode ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->uiManufacturerCode ) },
    { PGN_eTYPE_BIT,  32,   3, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceLower ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceLower ) },
    { PGN_eTYPE_BIT,  35,   5, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceUpper ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucDeviceInstanceUpper ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceFunction ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceFunction ) },
    { PGN_eTYPE_BIT,  48,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucRsvBit ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucRsvBit ) },
    { PGN_eTYPE_BIT,  49,   7, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceClass ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->teDeviceClass ) },
    { PGN_eTYPE_BIT,  56,   4, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSystemInstance ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSystemInstance ) },
    { PGN_eTYPE_BIT,  60,   3, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->teIndustryGroup ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->teIndustryGroup ) },
    { PGN_eTYPE_BIT,  63,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSelfCfgAddr ) ), sizeof( ((N2K_tzPGN_ISO_ADDR_CLAIM *)NULL )->ucSelfCfgAddr ) }
};

// ISO Commanded Address
static const PGN_tzFIELD_DESC XT_FAR azIsoCmdAddrFields[] =
{
    { PGN_eTYPE_BIT,   0,  21, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ulUniqueNumber ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ulUniqueNumber ) },
    { PGN_eTYPE_BIT,  21,  11, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->uiManufacturerCode ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->uiManufacturerCode ) },
    { PGN_eTYPE_BIT,  32,   3, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceLower ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceLower ) },
    { PGN_eTYPE_BIT,  35,   5, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceUpper ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucDeviceInstanceUpper ) },
    { PGN_eTYPE_UCHAR,  40,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceFunction ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceFunction ) },
    { PGN_eTYPE_BIT,  48,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucRsvBit ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucRsvBit ) },
    { PGN_eTYPE_BIT,  49,   7, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceClass ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->teDeviceClass ) },
    { PGN_eTYPE_BIT,  56,   4, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucSystemInstance ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucSystemInstance ) },
    { PGN_eTYPE_BIT,  60,   3, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->teIndustryGroup ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->teIndustryGroup ) },
    { PGN_eTYPE_BIT,  63,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucSelfCfgAddr ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucSelfCfgAddr ) },
    { PGN_eTYPE_UCHAR,  64,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucPrefSrcAddr ) ), sizeof( ((N2K_tzPGN_ISO_CMD_ADDR *)NULL )->ucPrefSrcAddr ) }
};

// ISO Request
static const PGN_tzFIELD_DESC XT_FAR azIsoReqFields[] =
{
    { PGN_eTYPE_BIT,   0,  24, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_REQ *)NULL )->ulParmGrpNum ) ), sizeof( ((N2K_tzPGN_ISO_REQ *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - Abort
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManAbortFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ucAbortGroupFunctionCode ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ucAbortGroupFunctionCode ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ulParmGrpNum ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_ABORT *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - BAM
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManBamFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucBamGroupFunctionCode ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucBamGroupFunctionCode ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->uiTotalMsgSz ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->uiTotalMsgSz ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucTotalNumFramesToBeSent ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ucTotalNumFramesToBeSent ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ulParmGrpNum ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_BAM *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - CTS
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManCtsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucCtsGroupFunctionCode ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucCtsGroupFunctionCode ) },
    { PGN_eTYPE_UCHAR,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumFramesThatCanBeSent ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumFramesThatCanBeSent ) },
    { PGN_eTYPE_UCHAR,  16,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumNextFrameToBeSent ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ucNumNextFrameToBeSent ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ulParmGrpNum ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_CTS *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - EOM
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManEomFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucEomGroupFunctionCode ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucEomGroupFunctionCode ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->uiTotalMsgSz ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->uiTotalMsgSz ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucTotalNumFramesRxed ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ucTotalNumFramesRxed ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ulParmGrpNum ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_EOM *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Connection Management - RTS
static const PGN_tzFIELD_DESC XT_FAR azIsoTpConnManRtsFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucRtsGroupFunctionCode ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucRtsGroupFunctionCode ) },
    { PGN_eTYPE_UINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->uiTotalMsgSz ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->uiTotalMsgSz ) },
    { PGN_eTYPE_UCHAR,  24,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucTotalNumFramesXmit ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ucTotalNumFramesXmit ) },
    { PGN_eTYPE_BIT,  40,  24, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ulParmGrpNum ) ), sizeof( ((N2K_tzPGN_ISO_TP_CONN_MAN_RTS *)NULL )->ulParmGrpNum ) }
};

// ISO Transport Protocol, Data Transfer
static const PGN_tzFIELD_DESC XT_FAR azIsoTpXferFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_XFER *)NULL )->ucSeqNumMultiPacketFrame ) ), sizeof( ((N2K_tzPGN_ISO_TP_XFER *)NULL )->ucSeqNumMultiPacketFrame ) },
    { PGN_eTYPE_UCHAR,   8,   7, (uint16)( (uint32)&( ((N2K_tzPGN_ISO_TP_XFER *)NULL )->aucMultiPacketPacketizedData ) ), sizeof( ((N2K_tzPGN_ISO_TP_XFER *)NULL )->aucMultiPacketPacketizedData ) }
};

// PGN List - Received PGN's Group Function
static const PGN_tzFIELD_DESC XT_FAR azPgnListRxFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PGN_LIST_RX *)NULL )->teRxedPgnGroupFunctionCode ) ), sizeof( ((N2K_tzPGN_PGN_LIST_RX *)NULL )->teRxedPgnGroupFunctionCode ) },
    { PGN_eTYPE_SINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PGN_LIST_RX *)NULL )->uiExtraCount ) ), sizeof( ((N2K_tzPGN_PGN_LIST_RX *)NULL )->uiExtraCount ) },
    { PGN_eTYPE_POINTER,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PGN_LIST_RX *)NULL )->ptzExtra ) ), sizeof( ((N2K_tzPGN_PGN_LIST_RX *)NULL )->ptzExtra ) }
};

static const PGN_tzFIELD_DESC XT_FAR azPgnListRxExtraFields[] =
{
    { PGN_eTYPE_BIT,   0,  24, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_PGN_LIST_RX *)NULL )->ulRxPgns ) ), sizeof( ((N2K_tzPGN_EXTRA_PGN_LIST_RX *)NULL )->ulRxPgns ) }
};

// PGN List - Transmitted PGN's Group Function
static const PGN_tzFIELD_DESC XT_FAR azPgnListTxFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PGN_LIST_TX *)NULL )->teTXedPgnGroupFunctionCode ) ), sizeof( ((N2K_tzPGN_PGN_LIST_TX *)NULL )->teTXedPgnGroupFunctionCode ) },
    { PGN_eTYPE_SINT,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PGN_LIST_TX *)NULL )->uiExtraCount ) ), sizeof( ((N2K_tzPGN_PGN_LIST_TX *)NULL )->uiExtraCount ) },
    { PGN_eTYPE_POINTER,   8,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PGN_LIST_TX *)NULL )->ptzExtra ) ), sizeof( ((N2K_tzPGN_PGN_LIST_TX *)NULL )->ptzExtra ) }
};

static const PGN_tzFIELD_DESC XT_FAR azPgnListTxExtraFields[] =
{
    { PGN_eTYPE_BIT,   0,  24, (uint16)( (uint32)&( ((N2K_tzPGN_EXTRA_PGN_LIST_TX *)NULL )->ulTXPgns ) ), sizeof( ((N2K_tzPGN_EXTRA_PGN_LIST_TX *)NULL )->ulTXPgns ) }
};

// Product Information
static const PGN_tzFIELD_DESC XT_FAR azProdInfFields[] =
{
    { PGN_eTYPE_UINT,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->uiNmea2kDbVer ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->uiNmea2kDbVer ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->uiNmeaMfgProdCode ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->uiNmeaMfgProdCode ) },
    { PGN_eTYPE_SCHAR,  32,  32, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgModelId ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgModelId ) },
    { PGN_eTYPE_SCHAR, 288,  32, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgSwVerCode ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgSwVerCode ) },
    { PGN_eTYPE_SCHAR, 544,  32, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgModelVer ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgModelVer ) },
    { PGN_eTYPE_SCHAR, 800,  32, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgModelSerNo ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->aucMfgModelSerNo ) },
    { PGN_eTYPE_UCHAR, 1056,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->teNmea2kCertLvl ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->teNmea2kCertLvl ) },
    { PGN_eTYPE_UCHAR, 1064,   1, (uint16)( (uint32)&( ((N2K_tzPGN_PROD_INF *)NULL )->ucLoadEquivalency ) ), sizeof( ((N2K_tzPGN_PROD_INF *)NULL )->ucLoadEquivalency ) }
};

// System Time
static const PGN_tzFIELD_DESC XT_FAR azSysTimeFields[] =
{
    { PGN_eTYPE_UCHAR,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_SYS_TIME *)NULL )->ucSid ) ), sizeof( ((N2K_tzPGN_SYS_TIME *)NULL )->ucSid ) },
    { PGN_eTYPE_BIT,   8,   4, (uint16)( (uint32)&( ((N2K_tzPGN_SYS_TIME *)NULL )->teSource ) ), sizeof( ((N2K_tzPGN_SYS_TIME *)NULL )->teSource ) },
    { PGN_eTYPE_UINT,  16,   1, (uint16)( (uint32)&( ((N2K_tzPGN_SYS_TIME *)NULL )->uiDate ) ), sizeof( ((N2K_tzPGN_SYS_TIME *)NULL )->uiDate ) },
    { PGN_eTYPE_ULONG,  32,   1, (uint16)( (uint32)&( ((N2K_tzPGN_SYS_TIME *)NULL )->ulTime ) ), sizeof( ((N2K_tzPGN_SYS_TIME *)NULL )->ulTime ) }
};

// Time and Date
static const PGN_tzFIELD_DESC XT_FAR azTimeDateFields[] =
{
    { PGN_eTYPE_UINT,   0,   1, (uint16)( (uint32)&( ((N2K_tzPGN_TIME_DATE *)NULL )->uiDate ) ), sizeof( ((N2K_tzPGN_TIME_DATE *)NULL )->uiDate ) },
    { PGN_eTYPE_ULONG,  16,   1, (uint16)( (uint32)&( ((N2K_tzPGN_TIME_DATE *)NULL )->ulTime ) ), sizeof( ((N2K_tzPGN_TIME_DATE *)NULL )->ulTime ) },
    { PGN_eTYPE_SINT,  48,   1, (uint16)( (uint32)&( ((N2K_tzPGN_TIME_DATE *)NULL )->siLocalOffs ) ), sizeof( ((N2K_tzPGN_TIME_DATE *)NULL )->siLocalOffs ) }
};

// Describe the descriptor of each PGN

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescAcInSts =
{
        -1,
        6,
        NULL,
        N2K_mSEND_AC_IN_STS,
        N2K_DLC_AC_IN_STS,
        sizeof( N2K_tzPGN_AC_IN_STS ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcInStsFields,
        N2K_DLC_EXTRA_AC_IN_STS,
        sizeof( N2K_tzPGN_EXTRA_AC_IN_STS ),
        9,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcInStsExtraFields
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescAcOutSts =
{
        -1,
        6,
        NULL,
        N2K_mSEND_AC_OUT_STS,
        N2K_DLC_AC_OUT_STS,
        sizeof( N2K_tzPGN_AC_OUT_STS ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcOutStsFields,
        N2K_DLC_EXTRA_AC_OUT_STS,
        sizeof( N2K_tzPGN_EXTRA_AC_OUT_STS ),
        8,
        (const PGN_tzFIELD_DESC * XT_FAR) azAcOutStsExtraFields
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescAgsSts =
{
        -1,
        6,
        NULL,
        N2K_mSEND_AGS_STS,
        N2K_DLC_AGS_STS,
        sizeof( N2K_tzPGN_AGS_STS ),
        6,
        (const PGN_tzFIELD_DESC * XT_FAR) azAgsStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescBattDetailSts =
{
        -1,
        6,
        NULL,
        N2K_mSEND_BATT_DETAIL_STS,
        N2K_DLC_BATT_DETAIL_STS,
        sizeof( N2K_tzPGN_BATT_DETAIL_STS ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattDetailStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescBattSts =
{
        -1,
        6,
        NULL,
        N2K_mSEND_BATT_STS,
        N2K_DLC_BATT_STS,
        sizeof( N2K_tzPGN_BATT_STS ),
        5,
        (const PGN_tzFIELD_DESC * XT_FAR) azBattStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescChgSts =
{
        -1,
        6,
        NULL,
        N2K_mSEND_CHG_STS,
        N2K_DLC_CHG_STS,
        sizeof( N2K_tzPGN_CHG_STS ),
        7,
        (const PGN_tzFIELD_DESC * XT_FAR) azChgStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescInvSts =
{
        -1,
        6,
        NULL,
        N2K_mSEND_INV_STS,
        N2K_DLC_INV_STS,
        sizeof( N2K_tzPGN_INV_STS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azInvStsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoAck =
{
        -1,
        6,
        N2K_mRECV_ISO_ACK,
        N2K_mSEND_ISO_ACK,
        N2K_DLC_ISO_ACK,
        sizeof( N2K_tzPGN_ISO_ACK ),
        3,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoAckFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoAddrClaim =
{
        -1,
        6,
        N2K_mRECV_ISO_ADDR_CLAIM,
        N2K_mSEND_ISO_ADDR_CLAIM,
        N2K_DLC_ISO_ADDR_CLAIM,
        sizeof( N2K_tzPGN_ISO_ADDR_CLAIM ),
        10,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoAddrClaimFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoCmdAddr =
{
        -1,
        6,
        N2K_mRECV_ISO_CMD_ADDR,
        N2K_mSEND_ISO_CMD_ADDR,
        N2K_DLC_ISO_CMD_ADDR,
        sizeof( N2K_tzPGN_ISO_CMD_ADDR ),
        11,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoCmdAddrFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoReq =
{
        -1,
        6,
        N2K_mRECV_ISO_REQ,
        N2K_mSEND_ISO_REQ,
        N2K_DLC_ISO_REQ,
        sizeof( N2K_tzPGN_ISO_REQ ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoReqFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoTpConnManAbort =
{
        0,
        7,
        N2K_mRECV_ISO_TP_CONN_MAN_ABORT,
        N2K_mSEND_ISO_TP_CONN_MAN_ABORT,
        N2K_DLC_ISO_TP_CONN_MAN_ABORT,
        sizeof( N2K_tzPGN_ISO_TP_CONN_MAN_ABORT ),
        2,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManAbortFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoTpConnManBam =
{
        0,
        7,
        N2K_mRECV_ISO_TP_CONN_MAN_BAM,
        N2K_mSEND_ISO_TP_CONN_MAN_BAM,
        N2K_DLC_ISO_TP_CONN_MAN_BAM,
        sizeof( N2K_tzPGN_ISO_TP_CONN_MAN_BAM ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManBamFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoTpConnManCts =
{
        0,
        7,
        N2K_mRECV_ISO_TP_CONN_MAN_CTS,
        N2K_mSEND_ISO_TP_CONN_MAN_CTS,
        N2K_DLC_ISO_TP_CONN_MAN_CTS,
        sizeof( N2K_tzPGN_ISO_TP_CONN_MAN_CTS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManCtsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoTpConnManEom =
{
        0,
        7,
        N2K_mRECV_ISO_TP_CONN_MAN_EOM,
        N2K_mSEND_ISO_TP_CONN_MAN_EOM,
        N2K_DLC_ISO_TP_CONN_MAN_EOM,
        sizeof( N2K_tzPGN_ISO_TP_CONN_MAN_EOM ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManEomFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoTpConnManRts =
{
        0,
        7,
        N2K_mRECV_ISO_TP_CONN_MAN_RTS,
        N2K_mSEND_ISO_TP_CONN_MAN_RTS,
        N2K_DLC_ISO_TP_CONN_MAN_RTS,
        sizeof( N2K_tzPGN_ISO_TP_CONN_MAN_RTS ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpConnManRtsFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescIsoTpXfer =
{
        -1,
        7,
        N2K_mRECV_ISO_TP_XFER,
        N2K_mSEND_ISO_TP_XFER,
        N2K_DLC_ISO_TP_XFER,
        sizeof( N2K_tzPGN_ISO_TP_XFER ),
        2,
        (const PGN_tzFIELD_DESC * XT_FAR) azIsoTpXferFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescPgnListRx =
{
        0,
        6,
        NULL,
        N2K_mSEND_PGN_LIST_RX,
        N2K_DLC_PGN_LIST_RX,
        sizeof( N2K_tzPGN_PGN_LIST_RX ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azPgnListRxFields,
        N2K_DLC_EXTRA_PGN_LIST_RX,
        sizeof( N2K_tzPGN_EXTRA_PGN_LIST_RX ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azPgnListRxExtraFields
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescPgnListTx =
{
        0,
        6,
        NULL,
        N2K_mSEND_PGN_LIST_TX,
        N2K_DLC_PGN_LIST_TX,
        sizeof( N2K_tzPGN_PGN_LIST_TX ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azPgnListTxFields,
        N2K_DLC_EXTRA_PGN_LIST_TX,
        sizeof( N2K_tzPGN_EXTRA_PGN_LIST_TX ),
        1,
        (const PGN_tzFIELD_DESC * XT_FAR) azPgnListTxExtraFields
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescProdInf =
{
        -1,
        6,
        N2K_mRECV_PROD_INF,
        N2K_mSEND_PROD_INF,
        N2K_DLC_PROD_INF,
        sizeof( N2K_tzPGN_PROD_INF ),
        8,
        (const PGN_tzFIELD_DESC * XT_FAR) azProdInfFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescSysTime =
{
        -1,
        3,
        N2K_mRECV_SYS_TIME,
        N2K_mSEND_SYS_TIME,
        N2K_DLC_SYS_TIME,
        sizeof( N2K_tzPGN_SYS_TIME ),
        4,
        (const PGN_tzFIELD_DESC * XT_FAR) azSysTimeFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

static const PGN_tzPGN_DESC XT_FAR N2K_tzDescTimeDate =
{
        -1,
        3,
        N2K_mRECV_TIME_DATE,
        N2K_mSEND_TIME_DATE,
        N2K_DLC_TIME_DATE,
        sizeof( N2K_tzPGN_TIME_DATE ),
        3,
        (const PGN_tzFIELD_DESC * XT_FAR) azTimeDateFields,
        0,
        0,
        0,
        (const PGN_tzFIELD_DESC * XT_FAR) NULL
};

#ifndef WIN32
#pragma CONST_SEG DEFAULT
#endif

// List of receivable PGNs
const uint32 N2K_kaulRX_PGN_LIST[] = 
{
	N2K_PGN_ISO_ACK,
	N2K_PGN_ISO_REQ,
	N2K_PGN_ISO_TP_XFER,
	N2K_PGN_ISO_TP_CONN_MAN,
	N2K_PGN_ISO_ADDR_CLAIM,
	N2K_PGN_ISO_CMD_ADDR,
	N2K_PGN_SYS_TIME,
	N2K_PGN_PROD_INF,
	N2K_PGN_TIME_DATE,
};

uint16 N2KPGNTBL_fnSizeOfRxPgnList( void )
{
    return ( XT_mDIM( N2K_kaulRX_PGN_LIST ) );
}

// List of Transmittable PGNs
const uint32 N2K_kaulTX_PGN_LIST[] = 
{
	N2K_PGN_ISO_ACK,
	N2K_PGN_ISO_REQ,
	N2K_PGN_ISO_TP_XFER,
	N2K_PGN_ISO_TP_CONN_MAN,
	N2K_PGN_ISO_ADDR_CLAIM,
	N2K_PGN_ISO_CMD_ADDR,
	N2K_PGN_PGN_LIST,
	N2K_PGN_SYS_TIME,
	N2K_PGN_PROD_INF,
	N2K_PGN_BATT_STS,
	N2K_PGN_TIME_DATE,
	N2K_PGN_BATT_DETAIL_STS,
	N2K_PGN_INV_STS,
	N2K_PGN_AGS_STS,
	N2K_PGN_CHG_STS,
	N2K_PGN_AC_OUT_STS,
	N2K_PGN_AC_IN_STS,
};

uint16 N2KPGNTBL_fnSizeOfTxPgnList( void )
{
    return ( XT_mDIM( N2K_kaulTX_PGN_LIST ) );
}

// List of all PGNS with descriptors for those used by PROTOCOL_NMEA2000
const PGN_tzPGN_INFO N2K_katzALL_PGN_LIST[] =
{
    { N2K_PGN_ISO_ACK,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_ACK,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoAck },

    { N2K_PGN_ISO_REQ,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_REQ,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoReq },

    { N2K_PGN_ISO_TP_XFER,              -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoTpXfer },

    { N2K_PGN_ISO_TP_CONN_MAN,          16,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoTpConnManRts },

    { N2K_PGN_ISO_TP_CONN_MAN,          17,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoTpConnManCts },

    { N2K_PGN_ISO_TP_CONN_MAN,          19,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoTpConnManEom },

    { N2K_PGN_ISO_TP_CONN_MAN,          32,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoTpConnManBam },

    { N2K_PGN_ISO_TP_CONN_MAN,         255,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_GFN,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoTpConnManAbort },

    { N2K_PGN_ISO_ADDR_CLAIM,           -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoAddrClaim },

    { N2K_PGN_ISO_CMD_ADDR,             -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_DNY | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX,
        PGN_PG_TYPE_CMD,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescIsoCmdAddr },

    { N2K_PGN_PGN_LIST,                  0,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_GFN,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescPgnListTx },

    { N2K_PGN_PGN_LIST,                  1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU1 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_GFN,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescPgnListRx },

    { N2K_PGN_SYS_TIME,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescSysTime },

    { N2K_PGN_PROD_INF,                 -1,        0,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescProdInf },

    { N2K_PGN_BATT_STS,                 -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescBattSts },

    { N2K_PGN_TIME_DATE,                -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_RX | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_CMD,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescTimeDate },

    { N2K_PGN_BATT_DETAIL_STS,          -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescBattDetailSts },

    { N2K_PGN_INV_STS,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescInvSts },

    { N2K_PGN_AGS_STS,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_NAK | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescAgsSts },

    { N2K_PGN_CHG_STS,                  -1,        PGN_NOT_FASTPACKET,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescChgSts },

    { N2K_PGN_AC_OUT_STS,               -1,        1,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescAcOutSts },

    { N2K_PGN_AC_IN_STS,                -1,        2,
         PGN_FLAG_PDU2 | PGN_FLAG_RX_IGN | PGN_FLAG_RESP_TX_PGN | PGN_FLAG_NRSP_TX_NAK | PGN_FLAG_TX | PGN_FLAG_REQ,
        PGN_PG_TYPE_RSP,
        ( const PGN_tzPGN_DESC * XT_FAR) &N2K_tzDescAcInSts },

};

uint16 N2KPGNTBL_fnSizeOfAllPgnList( void )
{
    return ( XT_mDIM( N2K_katzALL_PGN_LIST ) );
}

// Number of entries in dynamic support arrays rounded up to byte boundary
#define   N2K_DYNAMIC_COUNT    ( ( XT_mDIM( N2K_katzALL_PGN_LIST ) + XT_BITS_PER_BYTE - 1 ) / XT_BITS_PER_BYTE )

uchar8 N2K_aucDynamicRx[ N2K_DYNAMIC_COUNT ];

uint16 N2KPGNTBL_fnSizeOfDynRxLists( void )
{
    return ( XT_mDIM( N2K_aucDynamicRx ) );
}

//*****************************************************************************
// End of file.
//! @}
//*****************************************************************************
